//
// FilesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class FilesAPI {

    /**
     Delete files
     
     - parameter chatDeleteFilesRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatDeleteFiles(chatDeleteFilesRequest: ChatDeleteFilesRequest) async throws -> AnyCodable {
        return try await chatDeleteFilesWithRequestBuilder(chatDeleteFilesRequest: chatDeleteFilesRequest).execute().body
    }

    /**
     Delete files
     - DELETE /v1/chat/files
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter chatDeleteFilesRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func chatDeleteFilesWithRequestBuilder(chatDeleteFilesRequest: ChatDeleteFilesRequest) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/chat/files"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: chatDeleteFilesRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List user files
     
     - returns: [ChatFile]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetFiles() async throws -> [ChatFile] {
        return try await chatGetFilesWithRequestBuilder().execute().body
    }

    /**
     List user files
     - GET /v1/chat/files
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<[ChatFile]> 
     */
    open class func chatGetFilesWithRequestBuilder() -> RequestBuilder<[ChatFile]> {
        let localVariablePath = "/v1/chat/files"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ChatFile]>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get files for an agent
     
     - parameter agentId: (path)  
     - returns: [ChatFile]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetFilesAgentByagentId(agentId: String) async throws -> [ChatFile] {
        return try await chatGetFilesAgentByagentIdWithRequestBuilder(agentId: agentId).execute().body
    }

    /**
     Get files for an agent
     - GET /v1/chat/files/agent/{agent_id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter agentId: (path)  
     - returns: RequestBuilder<[ChatFile]> 
     */
    open class func chatGetFilesAgentByagentIdWithRequestBuilder(agentId: String) -> RequestBuilder<[ChatFile]> {
        var localVariablePath = "/v1/chat/files/agent/{agent_id}"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{agent_id}", with: agentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ChatFile]>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Download code execution output
     
     - parameter sessionId: (path)  
     - parameter fileId: (path)  
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetFilesCodeDownloadBysessionIdByfileid(sessionId: String, fileId: String) async throws -> URL {
        return try await chatGetFilesCodeDownloadBysessionIdByfileidWithRequestBuilder(sessionId: sessionId, fileId: fileId).execute().body
    }

    /**
     Download code execution output
     - GET /v1/chat/files/code/download/{session_id}/{fileId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter sessionId: (path)  
     - parameter fileId: (path)  
     - returns: RequestBuilder<URL> 
     */
    open class func chatGetFilesCodeDownloadBysessionIdByfileidWithRequestBuilder(sessionId: String, fileId: String) -> RequestBuilder<URL> {
        var localVariablePath = "/v1/chat/files/code/download/{session_id}/{fileId}"
        let sessionIdPreEscape = "\(APIHelper.mapValueToPathItem(sessionId))"
        let sessionIdPostEscape = sessionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{session_id}", with: sessionIdPostEscape, options: .literal, range: nil)
        let fileIdPreEscape = "\(APIHelper.mapValueToPathItem(fileId))"
        let fileIdPostEscape = fileIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fileId}", with: fileIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get file upload configuration
     
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetFilesConfig() async throws -> AnyCodable {
        return try await chatGetFilesConfigWithRequestBuilder().execute().body
    }

    /**
     Get file upload configuration
     - GET /v1/chat/files/config
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func chatGetFilesConfigWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/chat/files/config"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Download a file
     
     - parameter userId: (path)  
     - parameter fileId: (path)  
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetFilesDownloadByuseridByfileId(userId: String, fileId: String) async throws -> URL {
        return try await chatGetFilesDownloadByuseridByfileIdWithRequestBuilder(userId: userId, fileId: fileId).execute().body
    }

    /**
     Download a file
     - GET /v1/chat/files/download/{userId}/{file_id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter userId: (path)  
     - parameter fileId: (path)  
     - returns: RequestBuilder<URL> 
     */
    open class func chatGetFilesDownloadByuseridByfileIdWithRequestBuilder(userId: String, fileId: String) -> RequestBuilder<URL> {
        var localVariablePath = "/v1/chat/files/download/{userId}/{file_id}"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let fileIdPreEscape = "\(APIHelper.mapValueToPathItem(fileId))"
        let fileIdPostEscape = fileIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file_id}", with: fileIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upload a file
     
     - parameter file: (form)  
     - parameter fileId: (form)  (optional)
     - parameter endpoint: (form)  (optional)
     - parameter agentId: (form)  (optional)
     - parameter toolResource: (form)  (optional)
     - parameter messageFile: (form)  (optional)
     - returns: ChatFile
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatPostFiles(file: URL, fileId: String? = nil, endpoint: String? = nil, agentId: String? = nil, toolResource: String? = nil, messageFile: String? = nil) async throws -> ChatFile {
        return try await chatPostFilesWithRequestBuilder(file: file, fileId: fileId, endpoint: endpoint, agentId: agentId, toolResource: toolResource, messageFile: messageFile).execute().body
    }

    /**
     Upload a file
     - POST /v1/chat/files
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter file: (form)  
     - parameter fileId: (form)  (optional)
     - parameter endpoint: (form)  (optional)
     - parameter agentId: (form)  (optional)
     - parameter toolResource: (form)  (optional)
     - parameter messageFile: (form)  (optional)
     - returns: RequestBuilder<ChatFile> 
     */
    open class func chatPostFilesWithRequestBuilder(file: URL, fileId: String? = nil, endpoint: String? = nil, agentId: String? = nil, toolResource: String? = nil, messageFile: String? = nil) -> RequestBuilder<ChatFile> {
        let localVariablePath = "/v1/chat/files"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file.encodeToJSON(),
            "file_id": fileId?.encodeToJSON(),
            "endpoint": endpoint?.encodeToJSON(),
            "agent_id": agentId?.encodeToJSON(),
            "tool_resource": toolResource?.encodeToJSON(),
            "message_file": messageFile?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ChatFile>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Download a produced file by id
     
     - parameter id: (path)  
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func execDownloadFile(id: String) async throws -> URL {
        return try await execDownloadFileWithRequestBuilder(id: id).execute().body
    }

    /**
     Download a produced file by id
     - GET /v1/download/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<URL> 
     */
    open class func execDownloadFileWithRequestBuilder(id: String) -> RequestBuilder<URL> {
        var localVariablePath = "/v1/download/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List the files produced in a session
     
     - parameter sessionId: (path)  
     - returns: ExecListSessionFiles200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func execListSessionFiles(sessionId: String) async throws -> ExecListSessionFiles200Response {
        return try await execListSessionFilesWithRequestBuilder(sessionId: sessionId).execute().body
    }

    /**
     List the files produced in a session
     - GET /v1/files/{session_id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter sessionId: (path)  
     - returns: RequestBuilder<ExecListSessionFiles200Response> 
     */
    open class func execListSessionFilesWithRequestBuilder(sessionId: String) -> RequestBuilder<ExecListSessionFiles200Response> {
        var localVariablePath = "/v1/files/{session_id}"
        let sessionIdPreEscape = "\(APIHelper.mapValueToPathItem(sessionId))"
        let sessionIdPostEscape = sessionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{session_id}", with: sessionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ExecListSessionFiles200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upload a file into a session
     
     - parameter file: (form)  (optional)
     - parameter sessionId: (form)  (optional)
     - returns: ExecUploadFile200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func execUploadFile(file: URL? = nil, sessionId: String? = nil) async throws -> ExecUploadFile200Response {
        return try await execUploadFileWithRequestBuilder(file: file, sessionId: sessionId).execute().body
    }

    /**
     Upload a file into a session
     - POST /v1/upload
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter file: (form)  (optional)
     - parameter sessionId: (form)  (optional)
     - returns: RequestBuilder<ExecUploadFile200Response> 
     */
    open class func execUploadFileWithRequestBuilder(file: URL? = nil, sessionId: String? = nil) -> RequestBuilder<ExecUploadFile200Response> {
        let localVariablePath = "/v1/upload"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file?.encodeToJSON(),
            "session_id": sessionId?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ExecUploadFile200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
