//
// GitReposAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class GitReposAPI {

    /**
     Connect a git repo for sync (EE)
     
     - parameter autoConnectGitRepoRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func autoConnectGitRepo(autoConnectGitRepoRequest: AutoConnectGitRepoRequest) async throws -> AnyCodable {
        return try await autoConnectGitRepoWithRequestBuilder(autoConnectGitRepoRequest: autoConnectGitRepoRequest).execute().body
    }

    /**
     Connect a git repo for sync (EE)
     - POST /v1/auto/git-repos
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter autoConnectGitRepoRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func autoConnectGitRepoWithRequestBuilder(autoConnectGitRepoRequest: AutoConnectGitRepoRequest) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/auto/git-repos"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: autoConnectGitRepoRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List connected git repos (EE)
     
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func autoListGitRepos() async throws -> AnyCodable {
        return try await autoListGitReposWithRequestBuilder().execute().body
    }

    /**
     List connected git repos (EE)
     - GET /v1/auto/git-repos
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func autoListGitReposWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/auto/git-repos"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Connect a git repo for sync (EE)
     
     - parameter flowConnectGitRepoRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowConnectGitRepo(flowConnectGitRepoRequest: FlowConnectGitRepoRequest) async throws -> AnyCodable {
        return try await flowConnectGitRepoWithRequestBuilder(flowConnectGitRepoRequest: flowConnectGitRepoRequest).execute().body
    }

    /**
     Connect a git repo for sync (EE)
     - POST /v1/flow/git-repos
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter flowConnectGitRepoRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func flowConnectGitRepoWithRequestBuilder(flowConnectGitRepoRequest: FlowConnectGitRepoRequest) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/flow/git-repos"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: flowConnectGitRepoRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Disconnect a git repo (EE)
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowDisconnectGitRepo(id: String) async throws {
        return try await flowDisconnectGitRepoWithRequestBuilder(id: id).execute().body
    }

    /**
     Disconnect a git repo (EE)
     - DELETE /v1/flow/git-repos/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func flowDisconnectGitRepoWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/flow/git-repos/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List connected git repos (EE)
     
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowListGitRepos() async throws -> AnyCodable {
        return try await flowListGitReposWithRequestBuilder().execute().body
    }

    /**
     List connected git repos (EE)
     - GET /v1/flow/git-repos
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func flowListGitReposWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/flow/git-repos"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Pull flows from git (EE)
     
     - parameter id: (path)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowPullFromGitRepo(id: String) async throws -> AnyCodable {
        return try await flowPullFromGitRepoWithRequestBuilder(id: id).execute().body
    }

    /**
     Pull flows from git (EE)
     - POST /v1/flow/git-repos/{id}/pull
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func flowPullFromGitRepoWithRequestBuilder(id: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/flow/git-repos/{id}/pull"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Push flows to git (EE)
     
     - parameter id: (path)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowPushToGitRepo(id: String) async throws -> AnyCodable {
        return try await flowPushToGitRepoWithRequestBuilder(id: id).execute().body
    }

    /**
     Push flows to git (EE)
     - POST /v1/flow/git-repos/{id}/push
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func flowPushToGitRepoWithRequestBuilder(id: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/flow/git-repos/{id}/push"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
