//
// KeyValueAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class KeyValueAPI {

    /**
     Create KV bucket
     
     - parameter mqKVBucketConfig: (body)  
     - returns: MqKVBucket
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqCreateKVBucket(mqKVBucketConfig: MqKVBucketConfig) async throws -> MqKVBucket {
        return try await mqCreateKVBucketWithRequestBuilder(mqKVBucketConfig: mqKVBucketConfig).execute().body
    }

    /**
     Create KV bucket
     - POST /v1/mq/kv
     - Creates a new key-value bucket backed by a JetStream stream. Supports configurable history depth, TTL, and replication. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter mqKVBucketConfig: (body)  
     - returns: RequestBuilder<MqKVBucket> 
     */
    open class func mqCreateKVBucketWithRequestBuilder(mqKVBucketConfig: MqKVBucketConfig) -> RequestBuilder<MqKVBucket> {
        let localVariablePath = "/v1/mq/kv"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: mqKVBucketConfig)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqKVBucket>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete bucket
     
     - parameter bucket: (path) KV bucket name. 
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqDeleteKVBucket(bucket: String) async throws {
        return try await mqDeleteKVBucketWithRequestBuilder(bucket: bucket).execute().body
    }

    /**
     Delete bucket
     - DELETE /v1/mq/kv/{bucket}
     - Deletes the bucket and all its keys. Irreversible.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path) KV bucket name. 
     - returns: RequestBuilder<Void> 
     */
    open class func mqDeleteKVBucketWithRequestBuilder(bucket: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/mq/kv/{bucket}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete key
     
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (path) Key name (supports dotted hierarchy). 
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqDeleteKVEntry(bucket: String, key: String) async throws {
        return try await mqDeleteKVEntryWithRequestBuilder(bucket: bucket, key: key).execute().body
    }

    /**
     Delete key
     - DELETE /v1/mq/kv/{bucket}/{key}
     - Deletes the key by writing a tombstone marker. The key's history is preserved according to the bucket's history setting. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (path) Key name (supports dotted hierarchy). 
     - returns: RequestBuilder<Void> 
     */
    open class func mqDeleteKVEntryWithRequestBuilder(bucket: String, key: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/mq/kv/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get bucket info
     
     - parameter bucket: (path) KV bucket name. 
     - returns: MqKVBucket
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqGetKVBucket(bucket: String) async throws -> MqKVBucket {
        return try await mqGetKVBucketWithRequestBuilder(bucket: bucket).execute().body
    }

    /**
     Get bucket info
     - GET /v1/mq/kv/{bucket}
     - Returns bucket configuration and current state.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path) KV bucket name. 
     - returns: RequestBuilder<MqKVBucket> 
     */
    open class func mqGetKVBucketWithRequestBuilder(bucket: String) -> RequestBuilder<MqKVBucket> {
        var localVariablePath = "/v1/mq/kv/{bucket}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqKVBucket>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get value
     
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (path) Key name (supports dotted hierarchy). 
     - returns: MqKVEntry
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqGetKVEntry(bucket: String, key: String) async throws -> MqKVEntry {
        return try await mqGetKVEntryWithRequestBuilder(bucket: bucket, key: key).execute().body
    }

    /**
     Get value
     - GET /v1/mq/kv/{bucket}/{key}
     - Returns the current value for the key. The revision number is included in the X-MQ-Revision response header. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - responseHeaders: [X-MQ-Revision(Int), X-MQ-Created(Date), X-MQ-Operation(String)]
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (path) Key name (supports dotted hierarchy). 
     - returns: RequestBuilder<MqKVEntry> 
     */
    open class func mqGetKVEntryWithRequestBuilder(bucket: String, key: String) -> RequestBuilder<MqKVEntry> {
        var localVariablePath = "/v1/mq/kv/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqKVEntry>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get key history
     
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (path) Key name (supports dotted hierarchy). 
     - returns: MqGetKVHistory200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqGetKVHistory(bucket: String, key: String) async throws -> MqGetKVHistory200Response {
        return try await mqGetKVHistoryWithRequestBuilder(bucket: bucket, key: key).execute().body
    }

    /**
     Get key history
     - GET /v1/mq/kv/{bucket}/{key}/history
     - Returns all revisions of the key, from oldest to newest. The number of revisions kept is determined by the bucket's history setting. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (path) Key name (supports dotted hierarchy). 
     - returns: RequestBuilder<MqGetKVHistory200Response> 
     */
    open class func mqGetKVHistoryWithRequestBuilder(bucket: String, key: String) -> RequestBuilder<MqGetKVHistory200Response> {
        var localVariablePath = "/v1/mq/kv/{bucket}/{key}/history"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqGetKVHistory200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List KV buckets
     
     - parameter limit: (query) Maximum number of items to return. (optional, default to 100)
     - parameter offset: (query) Number of items to skip. (optional, default to 0)
     - returns: MqListKVBuckets200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqListKVBuckets(limit: Int? = nil, offset: Int? = nil) async throws -> MqListKVBuckets200Response {
        return try await mqListKVBucketsWithRequestBuilder(limit: limit, offset: offset).execute().body
    }

    /**
     List KV buckets
     - GET /v1/mq/kv
     - Returns all key-value buckets for the authenticated account.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter limit: (query) Maximum number of items to return. (optional, default to 100)
     - parameter offset: (query) Number of items to skip. (optional, default to 0)
     - returns: RequestBuilder<MqListKVBuckets200Response> 
     */
    open class func mqListKVBucketsWithRequestBuilder(limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<MqListKVBuckets200Response> {
        let localVariablePath = "/v1/mq/kv"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqListKVBuckets200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List keys in bucket
     
     - parameter bucket: (path) KV bucket name. 
     - parameter filter: (query) Key filter pattern (supports wildcards). (optional)
     - parameter limit: (query) Maximum number of items to return. (optional, default to 100)
     - parameter offset: (query) Number of items to skip. (optional, default to 0)
     - returns: MqListKVKeys200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqListKVKeys(bucket: String, filter: String? = nil, limit: Int? = nil, offset: Int? = nil) async throws -> MqListKVKeys200Response {
        return try await mqListKVKeysWithRequestBuilder(bucket: bucket, filter: filter, limit: limit, offset: offset).execute().body
    }

    /**
     List keys in bucket
     - GET /v1/mq/kv/{bucket}/keys
     - Returns all keys in the bucket, optionally filtered by pattern.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path) KV bucket name. 
     - parameter filter: (query) Key filter pattern (supports wildcards). (optional)
     - parameter limit: (query) Maximum number of items to return. (optional, default to 100)
     - parameter offset: (query) Number of items to skip. (optional, default to 0)
     - returns: RequestBuilder<MqListKVKeys200Response> 
     */
    open class func mqListKVKeysWithRequestBuilder(bucket: String, filter: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<MqListKVKeys200Response> {
        var localVariablePath = "/v1/mq/kv/{bucket}/keys"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "filter": (wrappedValue: filter?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqListKVKeys200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Put value
     
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (path) Key name (supports dotted hierarchy). 
     - parameter mqPutKVEntryRequest: (body)  
     - parameter xMQExpectedRevision: (header) Expected current revision for CAS. The put fails with 409 if the current revision does not match.  (optional)
     - returns: MqPutKVEntry200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqPutKVEntry(bucket: String, key: String, mqPutKVEntryRequest: MqPutKVEntryRequest, xMQExpectedRevision: Int? = nil) async throws -> MqPutKVEntry200Response {
        return try await mqPutKVEntryWithRequestBuilder(bucket: bucket, key: key, mqPutKVEntryRequest: mqPutKVEntryRequest, xMQExpectedRevision: xMQExpectedRevision).execute().body
    }

    /**
     Put value
     - PUT /v1/mq/kv/{bucket}/{key}
     - Sets the value for the key. Returns the new revision number. Use the X-MQ-Expected-Revision header for optimistic concurrency (CAS operation). 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (path) Key name (supports dotted hierarchy). 
     - parameter mqPutKVEntryRequest: (body)  
     - parameter xMQExpectedRevision: (header) Expected current revision for CAS. The put fails with 409 if the current revision does not match.  (optional)
     - returns: RequestBuilder<MqPutKVEntry200Response> 
     */
    open class func mqPutKVEntryWithRequestBuilder(bucket: String, key: String, mqPutKVEntryRequest: MqPutKVEntryRequest, xMQExpectedRevision: Int? = nil) -> RequestBuilder<MqPutKVEntry200Response> {
        var localVariablePath = "/v1/mq/kv/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: mqPutKVEntryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-MQ-Expected-Revision": xMQExpectedRevision?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqPutKVEntry200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Watch bucket changes via SSE
     
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (query) Key pattern filter (supports wildcards). (optional)
     - parameter includeHistory: (query) Include all historical revisions before live updates. (optional, default to false)
     - returns: MqKVEntry
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqWatchKVBucket(bucket: String, key: String? = nil, includeHistory: Bool? = nil) async throws -> MqKVEntry {
        return try await mqWatchKVBucketWithRequestBuilder(bucket: bucket, key: key, includeHistory: includeHistory).execute().body
    }

    /**
     Watch bucket changes via SSE
     - GET /v1/mq/kv/{bucket}/watch
     - Opens a Server-Sent Events stream that emits KVEntry events for every change in the bucket. Optionally filter by key pattern. Delivers initial values followed by real-time updates. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path) KV bucket name. 
     - parameter key: (query) Key pattern filter (supports wildcards). (optional)
     - parameter includeHistory: (query) Include all historical revisions before live updates. (optional, default to false)
     - returns: RequestBuilder<MqKVEntry> 
     */
    open class func mqWatchKVBucketWithRequestBuilder(bucket: String, key: String? = nil, includeHistory: Bool? = nil) -> RequestBuilder<MqKVEntry> {
        var localVariablePath = "/v1/mq/kv/{bucket}/watch"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "key": (wrappedValue: key?.encodeToJSON(), isExplode: true),
            "include_history": (wrappedValue: includeHistory?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqKVEntry>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create a KV bucket
     
     - parameter bucket: (path)  
     - parameter pubsubKVBucketConfig: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func pubsubCreateKVBucket(bucket: String, pubsubKVBucketConfig: PubsubKVBucketConfig) async throws {
        return try await pubsubCreateKVBucketWithRequestBuilder(bucket: bucket, pubsubKVBucketConfig: pubsubKVBucketConfig).execute().body
    }

    /**
     Create a KV bucket
     - POST /v1/pubsub/kv/{bucket}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter pubsubKVBucketConfig: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func pubsubCreateKVBucketWithRequestBuilder(bucket: String, pubsubKVBucketConfig: PubsubKVBucketConfig) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/pubsub/kv/{bucket}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: pubsubKVBucketConfig)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a KV bucket
     
     - parameter bucket: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func pubsubDeleteKVBucket(bucket: String) async throws {
        return try await pubsubDeleteKVBucketWithRequestBuilder(bucket: bucket).execute().body
    }

    /**
     Delete a KV bucket
     - DELETE /v1/pubsub/kv/{bucket}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func pubsubDeleteKVBucketWithRequestBuilder(bucket: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/pubsub/kv/{bucket}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a key
     
     - parameter bucket: (path)  
     - parameter key: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func pubsubKvDelete(bucket: String, key: String) async throws {
        return try await pubsubKvDeleteWithRequestBuilder(bucket: bucket, key: key).execute().body
    }

    /**
     Delete a key
     - DELETE /v1/pubsub/kv/{bucket}/{key}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter key: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func pubsubKvDeleteWithRequestBuilder(bucket: String, key: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/pubsub/kv/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get a value
     
     - parameter bucket: (path)  
     - parameter key: (path)  
     - parameter revision: (query) Specific revision to retrieve (optional)
     - returns: PubsubKVEntry
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func pubsubKvGet(bucket: String, key: String, revision: Int? = nil) async throws -> PubsubKVEntry {
        return try await pubsubKvGetWithRequestBuilder(bucket: bucket, key: key, revision: revision).execute().body
    }

    /**
     Get a value
     - GET /v1/pubsub/kv/{bucket}/{key}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter key: (path)  
     - parameter revision: (query) Specific revision to retrieve (optional)
     - returns: RequestBuilder<PubsubKVEntry> 
     */
    open class func pubsubKvGetWithRequestBuilder(bucket: String, key: String, revision: Int? = nil) -> RequestBuilder<PubsubKVEntry> {
        var localVariablePath = "/v1/pubsub/kv/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "revision": (wrappedValue: revision?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PubsubKVEntry>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get key history
     
     - parameter bucket: (path)  
     - parameter key: (path)  
     - returns: PubsubKvHistory200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func pubsubKvHistory(bucket: String, key: String) async throws -> PubsubKvHistory200Response {
        return try await pubsubKvHistoryWithRequestBuilder(bucket: bucket, key: key).execute().body
    }

    /**
     Get key history
     - GET /v1/pubsub/kv/{bucket}/{key}/history
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter key: (path)  
     - returns: RequestBuilder<PubsubKvHistory200Response> 
     */
    open class func pubsubKvHistoryWithRequestBuilder(bucket: String, key: String) -> RequestBuilder<PubsubKvHistory200Response> {
        var localVariablePath = "/v1/pubsub/kv/{bucket}/{key}/history"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PubsubKvHistory200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set a value
     
     - parameter bucket: (path)  
     - parameter key: (path)  
     - parameter body: (body)  
     - returns: PubsubKvPut200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func pubsubKvPut(bucket: String, key: String, body: URL) async throws -> PubsubKvPut200Response {
        return try await pubsubKvPutWithRequestBuilder(bucket: bucket, key: key, body: body).execute().body
    }

    /**
     Set a value
     - PUT /v1/pubsub/kv/{bucket}/{key}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter key: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<PubsubKvPut200Response> 
     */
    open class func pubsubKvPutWithRequestBuilder(bucket: String, key: String, body: URL) -> RequestBuilder<PubsubKvPut200Response> {
        var localVariablePath = "/v1/pubsub/kv/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = ["body": body]

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/octet-stream",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PubsubKvPut200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
