//
// OAuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class OAuthAPI {

    /**
     Initiate Apple OAuth
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthApple() async throws {
        return try await chatGetOauthAppleWithRequestBuilder().execute().body
    }

    /**
     Initiate Apple OAuth
     - GET /oauth/apple
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthAppleWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/apple"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Initiate Discord OAuth
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthDiscord() async throws {
        return try await chatGetOauthDiscordWithRequestBuilder().execute().body
    }

    /**
     Initiate Discord OAuth
     - GET /oauth/discord
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthDiscordWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/discord"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Discord OAuth callback
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthDiscordCallback() async throws {
        return try await chatGetOauthDiscordCallbackWithRequestBuilder().execute().body
    }

    /**
     Discord OAuth callback
     - GET /oauth/discord/callback
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthDiscordCallbackWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/discord/callback"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     OAuth error handler
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthError() async throws {
        return try await chatGetOauthErrorWithRequestBuilder().execute().body
    }

    /**
     OAuth error handler
     - GET /oauth/error
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthErrorWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/error"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Initiate Facebook OAuth
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthFacebook() async throws {
        return try await chatGetOauthFacebookWithRequestBuilder().execute().body
    }

    /**
     Initiate Facebook OAuth
     - GET /oauth/facebook
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthFacebookWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/facebook"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Facebook OAuth callback
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthFacebookCallback() async throws {
        return try await chatGetOauthFacebookCallbackWithRequestBuilder().execute().body
    }

    /**
     Facebook OAuth callback
     - GET /oauth/facebook/callback
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthFacebookCallbackWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/facebook/callback"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Initiate GitHub OAuth
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthGithub() async throws {
        return try await chatGetOauthGithubWithRequestBuilder().execute().body
    }

    /**
     Initiate GitHub OAuth
     - GET /oauth/github
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthGithubWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/github"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GitHub OAuth callback
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthGithubCallback() async throws {
        return try await chatGetOauthGithubCallbackWithRequestBuilder().execute().body
    }

    /**
     GitHub OAuth callback
     - GET /oauth/github/callback
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthGithubCallbackWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/github/callback"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Initiate Google OAuth
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthGoogle() async throws {
        return try await chatGetOauthGoogleWithRequestBuilder().execute().body
    }

    /**
     Initiate Google OAuth
     - GET /oauth/google
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthGoogleWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/google"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Google OAuth callback
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthGoogleCallback() async throws {
        return try await chatGetOauthGoogleCallbackWithRequestBuilder().execute().body
    }

    /**
     Google OAuth callback
     - GET /oauth/google/callback
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthGoogleCallbackWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/google/callback"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Initiate OpenID Connect login
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthOpenid() async throws {
        return try await chatGetOauthOpenidWithRequestBuilder().execute().body
    }

    /**
     Initiate OpenID Connect login
     - GET /oauth/openid
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthOpenidWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/openid"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     OpenID Connect callback
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthOpenidCallback() async throws {
        return try await chatGetOauthOpenidCallbackWithRequestBuilder().execute().body
    }

    /**
     OpenID Connect callback
     - GET /oauth/openid/callback
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthOpenidCallbackWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/openid/callback"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Initiate SAML login
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatGetOauthSaml() async throws {
        return try await chatGetOauthSamlWithRequestBuilder().execute().body
    }

    /**
     Initiate SAML login
     - GET /oauth/saml
     - returns: RequestBuilder<Void> 
     */
    open class func chatGetOauthSamlWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/saml"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Apple OAuth callback
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatPostOauthAppleCallback() async throws {
        return try await chatPostOauthAppleCallbackWithRequestBuilder().execute().body
    }

    /**
     Apple OAuth callback
     - POST /oauth/apple/callback
     - returns: RequestBuilder<Void> 
     */
    open class func chatPostOauthAppleCallbackWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/apple/callback"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     SAML callback
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chatPostOauthSamlCallback() async throws {
        return try await chatPostOauthSamlCallbackWithRequestBuilder().execute().body
    }

    /**
     SAML callback
     - POST /oauth/saml/callback
     - returns: RequestBuilder<Void> 
     */
    open class func chatPostOauthSamlCallbackWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/saml/callback"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Begin an OAuth flow (returns the provider authorize URL)
     
     - parameter provider: (path)  
     - returns: IntegrationsConnectProvider200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func integrationsConnectProvider(provider: String) async throws -> IntegrationsConnectProvider200Response {
        return try await integrationsConnectProviderWithRequestBuilder(provider: provider).execute().body
    }

    /**
     Begin an OAuth flow (returns the provider authorize URL)
     - POST /v1/integrations/{provider}/connect
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter provider: (path)  
     - returns: RequestBuilder<IntegrationsConnectProvider200Response> 
     */
    open class func integrationsConnectProviderWithRequestBuilder(provider: String) -> RequestBuilder<IntegrationsConnectProvider200Response> {
        var localVariablePath = "/v1/integrations/{provider}/connect"
        let providerPreEscape = "\(APIHelper.mapValueToPathItem(provider))"
        let providerPostEscape = providerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{provider}", with: providerPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IntegrationsConnectProvider200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Revoke and forget an org's connection (idempotent)
     
     - parameter provider: (path)  
     - returns: IntegrationsDisconnectProvider200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func integrationsDisconnectProvider(provider: String) async throws -> IntegrationsDisconnectProvider200Response {
        return try await integrationsDisconnectProviderWithRequestBuilder(provider: provider).execute().body
    }

    /**
     Revoke and forget an org's connection (idempotent)
     - POST /v1/integrations/{provider}/disconnect
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter provider: (path)  
     - returns: RequestBuilder<IntegrationsDisconnectProvider200Response> 
     */
    open class func integrationsDisconnectProviderWithRequestBuilder(provider: String) -> RequestBuilder<IntegrationsDisconnectProvider200Response> {
        var localVariablePath = "/v1/integrations/{provider}/disconnect"
        let providerPreEscape = "\(APIHelper.mapValueToPathItem(provider))"
        let providerPostEscape = providerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{provider}", with: providerPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IntegrationsDisconnectProvider200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     OAuth return — seal tokens and redirect to console
     
     - parameter state: (query)  
     - parameter provider: (path)  
     - parameter code: (query)  (optional)
     - parameter error: (query)  (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func integrationsProviderCallback(state: String, provider: String, code: String? = nil, error: String? = nil) async throws {
        return try await integrationsProviderCallbackWithRequestBuilder(state: state, provider: provider, code: code, error: error).execute().body
    }

    /**
     OAuth return — seal tokens and redirect to console
     - GET /v1/integrations/{provider}/callback
     - Public, state-authed. The org comes only from the signed, single-use state. Always 302s back to the console (success or labeled failure).
     - parameter state: (query)  
     - parameter provider: (path)  
     - parameter code: (query)  (optional)
     - parameter error: (query)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func integrationsProviderCallbackWithRequestBuilder(state: String, provider: String, code: String? = nil, error: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/integrations/{provider}/callback"
        let providerPreEscape = "\(APIHelper.mapValueToPathItem(provider))"
        let providerPostEscape = providerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{provider}", with: providerPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "state": (wrappedValue: state.encodeToJSON(), isExplode: true),
            "code": (wrappedValue: code?.encodeToJSON(), isExplode: true),
            "error": (wrappedValue: error?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
