//
// ScansAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ScansAPI {

    /**
     Get scan report
     
     - parameter name: (path)  
     - parameter repo: (path)  
     - parameter digest: (path)  
     - returns: RegistryScanReport
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func registryGetScanReport(name: String, repo: String, digest: String) async throws -> RegistryScanReport {
        return try await registryGetScanReportWithRequestBuilder(name: name, repo: repo, digest: digest).execute().body
    }

    /**
     Get scan report
     - GET /v1/registry/projects/{name}/repositories/{repo}/artifacts/{digest}/scan/report
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter name: (path)  
     - parameter repo: (path)  
     - parameter digest: (path)  
     - returns: RequestBuilder<RegistryScanReport> 
     */
    open class func registryGetScanReportWithRequestBuilder(name: String, repo: String, digest: String) -> RequestBuilder<RegistryScanReport> {
        var localVariablePath = "/v1/registry/projects/{name}/repositories/{repo}/artifacts/{digest}/scan/report"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let repoPreEscape = "\(APIHelper.mapValueToPathItem(repo))"
        let repoPostEscape = repoPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{repo}", with: repoPostEscape, options: .literal, range: nil)
        let digestPreEscape = "\(APIHelper.mapValueToPathItem(digest))"
        let digestPostEscape = digestPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{digest}", with: digestPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RegistryScanReport>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Trigger vulnerability scan
     
     - parameter name: (path)  
     - parameter repo: (path)  
     - parameter digest: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func registryTriggerScan(name: String, repo: String, digest: String) async throws {
        return try await registryTriggerScanWithRequestBuilder(name: name, repo: repo, digest: digest).execute().body
    }

    /**
     Trigger vulnerability scan
     - POST /v1/registry/projects/{name}/repositories/{repo}/artifacts/{digest}/scan
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter name: (path)  
     - parameter repo: (path)  
     - parameter digest: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func registryTriggerScanWithRequestBuilder(name: String, repo: String, digest: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/registry/projects/{name}/repositories/{repo}/artifacts/{digest}/scan"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let repoPreEscape = "\(APIHelper.mapValueToPathItem(repo))"
        let repoPostEscape = repoPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{repo}", with: repoPostEscape, options: .literal, range: nil)
        let digestPreEscape = "\(APIHelper.mapValueToPathItem(digest))"
        let digestPostEscape = digestPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{digest}", with: digestPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get a scan with its findings
     
     - parameter id: (path)  
     - returns: SecuritySecurityGetScan200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func securitySecurityGetScan(id: String) async throws -> SecuritySecurityGetScan200Response {
        return try await securitySecurityGetScanWithRequestBuilder(id: id).execute().body
    }

    /**
     Get a scan with its findings
     - GET /v1/security/scans/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<SecuritySecurityGetScan200Response> 
     */
    open class func securitySecurityGetScanWithRequestBuilder(id: String) -> RequestBuilder<SecuritySecurityGetScan200Response> {
        var localVariablePath = "/v1/security/scans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SecuritySecurityGetScan200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List scans
     
     - parameter limit: (query)  (optional)
     - returns: SecuritySecurityListScans200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func securitySecurityListScans(limit: Int? = nil) async throws -> SecuritySecurityListScans200Response {
        return try await securitySecurityListScansWithRequestBuilder(limit: limit).execute().body
    }

    /**
     List scans
     - GET /v1/security/scans
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter limit: (query)  (optional)
     - returns: RequestBuilder<SecuritySecurityListScans200Response> 
     */
    open class func securitySecurityListScansWithRequestBuilder(limit: Int? = nil) -> RequestBuilder<SecuritySecurityListScans200Response> {
        let localVariablePath = "/v1/security/scans"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SecuritySecurityListScans200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submit a scan
     
     - parameter securityScanRequest: (body)  
     - returns: SecurityScan
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func securitySecuritySubmitScan(securityScanRequest: SecurityScanRequest) async throws -> SecurityScan {
        return try await securitySecuritySubmitScanWithRequestBuilder(securityScanRequest: securityScanRequest).execute().body
    }

    /**
     Submit a scan
     - POST /v1/security/scans
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter securityScanRequest: (body)  
     - returns: RequestBuilder<SecurityScan> 
     */
    open class func securitySecuritySubmitScanWithRequestBuilder(securityScanRequest: SecurityScanRequest) -> RequestBuilder<SecurityScan> {
        let localVariablePath = "/v1/security/scans"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: securityScanRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SecurityScan>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
