//
// SubjectsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SubjectsAPI {

    /**
     Get subject info
     
     - parameter subject: (path)  
     - returns: MqSubjectInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqGetSubjectInfo(subject: String) async throws -> MqSubjectInfo {
        return try await mqGetSubjectInfoWithRequestBuilder(subject: subject).execute().body
    }

    /**
     Get subject info
     - GET /v1/mq/subjects/{subject}/info
     - Returns detailed information about a specific subject, including subscriber count and message throughput. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter subject: (path)  
     - returns: RequestBuilder<MqSubjectInfo> 
     */
    open class func mqGetSubjectInfoWithRequestBuilder(subject: String) -> RequestBuilder<MqSubjectInfo> {
        var localVariablePath = "/v1/mq/subjects/{subject}/info"
        let subjectPreEscape = "\(APIHelper.mapValueToPathItem(subject))"
        let subjectPostEscape = subjectPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{subject}", with: subjectPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqSubjectInfo>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List active subjects
     
     - parameter limit: (query) Maximum number of items to return. (optional, default to 100)
     - parameter offset: (query) Number of items to skip. (optional, default to 0)
     - parameter filter: (query) Subject filter pattern (supports wildcards). (optional)
     - returns: MqListSubjects200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mqListSubjects(limit: Int? = nil, offset: Int? = nil, filter: String? = nil) async throws -> MqListSubjects200Response {
        return try await mqListSubjectsWithRequestBuilder(limit: limit, offset: offset, filter: filter).execute().body
    }

    /**
     List active subjects
     - GET /v1/mq/subjects
     - Returns all active subjects visible to the authenticated account, with subscriber counts and message rates. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter limit: (query) Maximum number of items to return. (optional, default to 100)
     - parameter offset: (query) Number of items to skip. (optional, default to 0)
     - parameter filter: (query) Subject filter pattern (supports wildcards). (optional)
     - returns: RequestBuilder<MqListSubjects200Response> 
     */
    open class func mqListSubjectsWithRequestBuilder(limit: Int? = nil, offset: Int? = nil, filter: String? = nil) -> RequestBuilder<MqListSubjects200Response> {
        let localVariablePath = "/v1/mq/subjects"
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
            "filter": (wrappedValue: filter?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MqListSubjects200Response>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
