//
// VersioningAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class VersioningAPI {

    /**
     Get versioning status
     
     - parameter bucket: (path)  
     - returns: S3VersioningConfig
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func s3GetBucketVersioning(bucket: String) async throws -> S3VersioningConfig {
        return try await s3GetBucketVersioningWithRequestBuilder(bucket: bucket).execute().body
    }

    /**
     Get versioning status
     - GET /v1/s3/{bucket}?versioning
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - returns: RequestBuilder<S3VersioningConfig> 
     */
    open class func s3GetBucketVersioningWithRequestBuilder(bucket: String) -> RequestBuilder<S3VersioningConfig> {
        var localVariablePath = "/v1/s3/{bucket}?versioning"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<S3VersioningConfig>.Type = HanzoAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set versioning status
     
     - parameter bucket: (path)  
     - parameter s3VersioningConfig: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func s3PutBucketVersioning(bucket: String, s3VersioningConfig: S3VersioningConfig) async throws {
        return try await s3PutBucketVersioningWithRequestBuilder(bucket: bucket, s3VersioningConfig: s3VersioningConfig).execute().body
    }

    /**
     Set versioning status
     - PUT /v1/s3/{bucket}?versioning
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter s3VersioningConfig: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func s3PutBucketVersioningWithRequestBuilder(bucket: String, s3VersioningConfig: S3VersioningConfig) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/s3/{bucket}?versioning"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = HanzoAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: s3VersioningConfig)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = HanzoAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
