//
// ActivityOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ActivityOut: Sendable, Codable, ParameterConvertible, Hashable {

    /** Data is the change log newest-first: who created, updated or deleted which key, when. */
    public var data: [ActivityRow]?

    public init(data: [ActivityRow]? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

