//
// AdminEnablementItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AdminEnablementItem: Sendable, Codable, ParameterConvertible, Hashable {

    public var betaOrgs: [String]?
    public var id: String?
    public var kind: String?
    /** off|beta|ga */
    public var state: String?
    public var updatedAt: Int?

    public init(betaOrgs: [String]? = nil, id: String? = nil, kind: String? = nil, state: String? = nil, updatedAt: Int? = nil) {
        self.betaOrgs = betaOrgs
        self.id = id
        self.kind = kind
        self.state = state
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case betaOrgs
        case id
        case kind
        case state
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(betaOrgs, forKey: .betaOrgs)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AdminEnablementItem: Identifiable {}
