//
// AdminEnablementBoard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AdminEnablementBoard: Sendable, Codable, ParameterConvertible, Hashable {

    /** Items is every item an operator has set a state on. An item nobody has touched is absent: it is generally available by default. */
    public var items: [AdminEnablementItem]?

    public init(items: [AdminEnablementItem]? = nil) {
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

