//
// AdminO11yGlobal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminO11yGlobal: Codable, JSONEncodable, Hashable {

    public var range: String?
    public var start: String?
    public var end: String?
    public var totals: AdminO11yTotals?
    public var series: [AdminO11ySeries]?
    public var logSeries: [AdminO11yLogPoint]?
    public var topOrgs: [AdminO11yOrgStat]?
    public var topModels: [AdminO11yModelStat]?
    public var topServices: [AdminO11ySvcStat]?
    public var llm: AdminO11yLLM?

    public init(range: String? = nil, start: String? = nil, end: String? = nil, totals: AdminO11yTotals? = nil, series: [AdminO11ySeries]? = nil, logSeries: [AdminO11yLogPoint]? = nil, topOrgs: [AdminO11yOrgStat]? = nil, topModels: [AdminO11yModelStat]? = nil, topServices: [AdminO11ySvcStat]? = nil, llm: AdminO11yLLM? = nil) {
        self.range = range
        self.start = start
        self.end = end
        self.totals = totals
        self.series = series
        self.logSeries = logSeries
        self.topOrgs = topOrgs
        self.topModels = topModels
        self.topServices = topServices
        self.llm = llm
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case range
        case start
        case end
        case totals
        case series
        case logSeries
        case topOrgs
        case topModels
        case topServices
        case llm
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(range, forKey: .range)
        try container.encodeIfPresent(start, forKey: .start)
        try container.encodeIfPresent(end, forKey: .end)
        try container.encodeIfPresent(totals, forKey: .totals)
        try container.encodeIfPresent(series, forKey: .series)
        try container.encodeIfPresent(logSeries, forKey: .logSeries)
        try container.encodeIfPresent(topOrgs, forKey: .topOrgs)
        try container.encodeIfPresent(topModels, forKey: .topModels)
        try container.encodeIfPresent(topServices, forKey: .topServices)
        try container.encodeIfPresent(llm, forKey: .llm)
    }
}

