//
// AdSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AdSummary: Sendable, Codable, ParameterConvertible, Hashable {

    /** Active is how many of those campaigns are in the active state. */
    public var active: Int64?
    /** Budget is the summed budget of every campaign in the org, in cents. */
    public var budget: Int64?
    /** Campaigns is how many campaigns the org has, in every state. */
    public var campaigns: Int64?
    /** Spend is the summed spend of every campaign in the org, in cents. */
    public var spend: Int64?

    public init(active: Int64? = nil, budget: Int64? = nil, campaigns: Int64? = nil, spend: Int64? = nil) {
        self.active = active
        self.budget = budget
        self.campaigns = campaigns
        self.spend = spend
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case active
        case budget
        case campaigns
        case spend
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(active, forKey: .active)
        try container.encodeIfPresent(budget, forKey: .budget)
        try container.encodeIfPresent(campaigns, forKey: .campaigns)
        try container.encodeIfPresent(spend, forKey: .spend)
    }
}

