//
// AffiliatesPayoutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for POST /v1/admin/affiliates/{id}/payout. */
public struct AffiliatesPayoutRequest: Codable, JSONEncodable, Hashable {

    /** Payout amount in USD cents (must be positive; cannot exceed pending commission). */
    public var amountCents: Int64
    /** Payout method. `credits` issues a commerce grant; any other value (wire/paypal/check/…) is record-only. */
    public var method: String
    /** Optional external reference for a cash payout. */
    public var reference: String?

    public init(amountCents: Int64, method: String, reference: String? = nil) {
        self.amountCents = amountCents
        self.method = method
        self.reference = reference
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amountCents
        case method
        case reference
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amountCents, forKey: .amountCents)
        try container.encode(method, forKey: .method)
        try container.encodeIfPresent(reference, forKey: .reference)
    }
}

