//
// AiEmbeddingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AiEmbeddingRequest: Codable, JSONEncodable, Hashable {

    public enum EncodingFormat: String, Codable, CaseIterable {
        case float = "float"
        case base64 = "base64"
    }
    public var model: String
    public var input: AnyCodable?
    public var encodingFormat: EncodingFormat?

    public init(model: String, input: AnyCodable?, encodingFormat: EncodingFormat? = nil) {
        self.model = model
        self.input = input
        self.encodingFormat = encodingFormat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case model
        case input
        case encodingFormat = "encoding_format"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(model, forKey: .model)
        try container.encode(input, forKey: .input)
        try container.encodeIfPresent(encodingFormat, forKey: .encodingFormat)
    }
}

