//
// Alert.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Alert: Sendable, Codable, ParameterConvertible, Hashable {

    public var createdAt: String?
    public var currency: String?
    public var enforce: Bool?
    public var id: String?
    public var over: Bool?
    public var period: String?
    public var periodSpentCents: Int64?
    public var project: String?
    public var rateLimitRpm: Int64?
    public var resetsAt: String?
    public var service: String?
    public var softPct: Int64?
    public var threshold: Int64?
    public var title: String?
    public var triggeredAt: String?
    public var updatedAt: String?
    public var userId: String?
    public var warn: Bool?

    public init(createdAt: String? = nil, currency: String? = nil, enforce: Bool? = nil, id: String? = nil, over: Bool? = nil, period: String? = nil, periodSpentCents: Int64? = nil, project: String? = nil, rateLimitRpm: Int64? = nil, resetsAt: String? = nil, service: String? = nil, softPct: Int64? = nil, threshold: Int64? = nil, title: String? = nil, triggeredAt: String? = nil, updatedAt: String? = nil, userId: String? = nil, warn: Bool? = nil) {
        self.createdAt = createdAt
        self.currency = currency
        self.enforce = enforce
        self.id = id
        self.over = over
        self.period = period
        self.periodSpentCents = periodSpentCents
        self.project = project
        self.rateLimitRpm = rateLimitRpm
        self.resetsAt = resetsAt
        self.service = service
        self.softPct = softPct
        self.threshold = threshold
        self.title = title
        self.triggeredAt = triggeredAt
        self.updatedAt = updatedAt
        self.userId = userId
        self.warn = warn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case currency
        case enforce
        case id
        case over
        case period
        case periodSpentCents
        case project
        case rateLimitRpm
        case resetsAt
        case service
        case softPct
        case threshold
        case title
        case triggeredAt
        case updatedAt
        case userId
        case warn
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(enforce, forKey: .enforce)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(over, forKey: .over)
        try container.encodeIfPresent(period, forKey: .period)
        try container.encodeIfPresent(periodSpentCents, forKey: .periodSpentCents)
        try container.encodeIfPresent(project, forKey: .project)
        try container.encodeIfPresent(rateLimitRpm, forKey: .rateLimitRpm)
        try container.encodeIfPresent(resetsAt, forKey: .resetsAt)
        try container.encodeIfPresent(service, forKey: .service)
        try container.encodeIfPresent(softPct, forKey: .softPct)
        try container.encodeIfPresent(threshold, forKey: .threshold)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(triggeredAt, forKey: .triggeredAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(warn, forKey: .warn)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Alert: Identifiable {}
