//
// AnalyticsLogin200ResponseUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsLogin200ResponseUser: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var username: String?
    public var role: String?
    public var createdAt: Date?
    public var isAdmin: Bool?

    public init(id: UUID? = nil, username: String? = nil, role: String? = nil, createdAt: Date? = nil, isAdmin: Bool? = nil) {
        self.id = id
        self.username = username
        self.role = role
        self.createdAt = createdAt
        self.isAdmin = isAdmin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case role
        case createdAt
        case isAdmin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(isAdmin, forKey: .isAdmin)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AnalyticsLogin200ResponseUser: Identifiable {}
