//
// ApproveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApproveRequest: Sendable, Codable, ParameterConvertible, Hashable {

    /** ID is the author to approve, from the path. */
    public var id: String?
    /** ShareBps overrides this author's royalty share, in basis points (0–10000). 0 keeps the platform default. A share change never rewrites history: existing ledger rows keep the share that was applied when they were written. */
    public var shareBps: Int?

    public init(id: String? = nil, shareBps: Int? = nil) {
        self.id = id
        self.shareBps = shareBps
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case shareBps
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(shareBps, forKey: .shareBps)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ApproveRequest: Identifiable {}
