//
// AuthzEnforceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An RBAC access tuple. */
public struct AuthzEnforceRequest: Codable, JSONEncodable, Hashable {

    /** Subject — the user or role requesting access. */
    public var sub: String
    /** Object — the resource being accessed. */
    public var obj: String
    /** Action — the operation on the object. */
    public var act: String

    public init(sub: String, obj: String, act: String) {
        self.sub = sub
        self.obj = obj
        self.act = act
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sub
        case obj
        case act
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sub, forKey: .sub)
        try container.encode(obj, forKey: .obj)
        try container.encode(act, forKey: .act)
    }
}

