//
// BoardItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BoardItem: Sendable, Codable, ParameterConvertible, Hashable {

    public var doctype: String?
    public var name: String?
    public var project: String?
    public var status: String?
    public var title: String?
    public var updatedAt: Int?

    public init(doctype: String? = nil, name: String? = nil, project: String? = nil, status: String? = nil, title: String? = nil, updatedAt: Int? = nil) {
        self.doctype = doctype
        self.name = name
        self.project = project
        self.status = status
        self.title = title
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case doctype
        case name
        case project
        case status
        case title
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(doctype, forKey: .doctype)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(project, forKey: .project)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

