//
// BotListUserStars200ResponseItemsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BotListUserStars200ResponseItemsInner: Codable, JSONEncodable, Hashable {

    public var skillId: UUID?
    public var skillSlug: String?
    public var skillDisplayName: String?
    public var skillSummary: String?
    public var starredAt: Date?

    public init(skillId: UUID? = nil, skillSlug: String? = nil, skillDisplayName: String? = nil, skillSummary: String? = nil, starredAt: Date? = nil) {
        self.skillId = skillId
        self.skillSlug = skillSlug
        self.skillDisplayName = skillDisplayName
        self.skillSummary = skillSummary
        self.starredAt = starredAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case skillId
        case skillSlug
        case skillDisplayName
        case skillSummary
        case starredAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(skillId, forKey: .skillId)
        try container.encodeIfPresent(skillSlug, forKey: .skillSlug)
        try container.encodeIfPresent(skillDisplayName, forKey: .skillDisplayName)
        try container.encodeIfPresent(skillSummary, forKey: .skillSummary)
        try container.encodeIfPresent(starredAt, forKey: .starredAt)
    }
}

