//
// BotPersonaVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BotPersonaVersion: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var personaId: UUID?
    public var version: String?
    public var createdAt: Date?

    public init(id: UUID? = nil, personaId: UUID? = nil, version: String? = nil, createdAt: Date? = nil) {
        self.id = id
        self.personaId = personaId
        self.version = version
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case personaId
        case version
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(personaId, forKey: .personaId)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BotPersonaVersion: Identifiable {}
