//
// CaptableCompanyUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CaptableCompanyUpdate: Sendable, Codable, ParameterConvertible, Hashable {

    public var incorporationCountry: JSONValue?
    public var incorporationState: JSONValue?
    public var incorporationType: JSONValue?
    public var name: JSONValue?

    public init(incorporationCountry: JSONValue? = nil, incorporationState: JSONValue? = nil, incorporationType: JSONValue? = nil, name: JSONValue? = nil) {
        self.incorporationCountry = incorporationCountry
        self.incorporationState = incorporationState
        self.incorporationType = incorporationType
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case incorporationCountry
        case incorporationState
        case incorporationType
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(incorporationCountry, forKey: .incorporationCountry)
        try container.encodeIfPresent(incorporationState, forKey: .incorporationState)
        try container.encodeIfPresent(incorporationType, forKey: .incorporationType)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

