//
// ChatGetAuth2faEnable200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatGetAuth2faEnable200Response: Codable, JSONEncodable, Hashable {

    public var otpauthUrl: String?
    public var secret: String?

    public init(otpauthUrl: String? = nil, secret: String? = nil) {
        self.otpauthUrl = otpauthUrl
        self.secret = secret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case otpauthUrl
        case secret
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(otpauthUrl, forKey: .otpauthUrl)
        try container.encodeIfPresent(secret, forKey: .secret)
    }
}

