//
// ChatPutKeysRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatPutKeysRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var value: String
    public var expiresAt: Date

    public init(name: String, value: String, expiresAt: Date) {
        self.name = name
        self.value = value
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case value
        case expiresAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(value, forKey: .value)
        try container.encode(expiresAt, forKey: .expiresAt)
    }
}

