//
// ChatTool.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatTool: Codable, JSONEncodable, Hashable {

    public var pluginKey: String?
    public var name: String?
    public var description: String?
    public var icon: String?
    public var authConfig: [AnyCodable]?
    public var authenticated: Bool?

    public init(pluginKey: String? = nil, name: String? = nil, description: String? = nil, icon: String? = nil, authConfig: [AnyCodable]? = nil, authenticated: Bool? = nil) {
        self.pluginKey = pluginKey
        self.name = name
        self.description = description
        self.icon = icon
        self.authConfig = authConfig
        self.authenticated = authenticated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pluginKey
        case name
        case description
        case icon
        case authConfig
        case authenticated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pluginKey, forKey: .pluginKey)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(authConfig, forKey: .authConfig)
        try container.encodeIfPresent(authenticated, forKey: .authenticated)
    }
}

