//
// CloudObjectUsage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CloudObjectUsage: Codable, JSONEncodable, Hashable {

    public var chatCount: Int64?
    public var currency: String?
    public var date: String?
    public var messageCount: Int64?
    public var price: Double?
    public var tokenCount: Int64?
    public var userCount: Int64?

    public init(chatCount: Int64? = nil, currency: String? = nil, date: String? = nil, messageCount: Int64? = nil, price: Double? = nil, tokenCount: Int64? = nil, userCount: Int64? = nil) {
        self.chatCount = chatCount
        self.currency = currency
        self.date = date
        self.messageCount = messageCount
        self.price = price
        self.tokenCount = tokenCount
        self.userCount = userCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatCount
        case currency
        case date
        case messageCount
        case price
        case tokenCount
        case userCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(chatCount, forKey: .chatCount)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(messageCount, forKey: .messageCount)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(tokenCount, forKey: .tokenCount)
        try container.encodeIfPresent(userCount, forKey: .userCount)
    }
}

