//
// CloudObjectUsageInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CloudObjectUsageInfo: Codable, JSONEncodable, Hashable {

    public var provider: String?
    public var startTime: String?
    public var tokenCount: Int64?

    public init(provider: String? = nil, startTime: String? = nil, tokenCount: Int64? = nil) {
        self.provider = provider
        self.startTime = startTime
        self.tokenCount = tokenCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case startTime
        case tokenCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(tokenCount, forKey: .tokenCount)
    }
}

