//
// CommerceGetOrderStatus200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CommerceGetOrderStatus200Response: Codable, JSONEncodable, Hashable {

    public var status: CommerceOrderStatus?
    public var paymentStatus: CommercePaymentStatus?

    public init(status: CommerceOrderStatus? = nil, paymentStatus: CommercePaymentStatus? = nil) {
        self.status = status
        self.paymentStatus = paymentStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case paymentStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(paymentStatus, forKey: .paymentStatus)
    }
}

