//
// CommerceAffiliate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CommerceAffiliate: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var userId: String?
    public var name: String?
    public var email: String?
    public var commission: CommerceAffiliateCommission?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: String? = nil, userId: String? = nil, name: String? = nil, email: String? = nil, commission: CommerceAffiliateCommission? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.userId = userId
        self.name = name
        self.email = email
        self.commission = commission
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId
        case name
        case email
        case commission
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(commission, forKey: .commission)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CommerceAffiliate: Identifiable {}
