//
// ConsoleListOrganizationProjects200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConsoleListOrganizationProjects200Response: Codable, JSONEncodable, Hashable {

    public var projects: [ConsoleListOrganizationProjects200ResponseProjectsInner]?

    public init(projects: [ConsoleListOrganizationProjects200ResponseProjectsInner]? = nil) {
        self.projects = projects
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projects
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projects, forKey: .projects)
    }
}

