//
// CreditGrant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreditGrant: Sendable, Codable, ParameterConvertible, Hashable {

    public var active: Bool?
    public var amountCents: Int?
    public var createdAt: String?
    public var currency: String?
    public var effectiveAt: String?
    public var expiresAt: String?
    public var id: String?
    public var name: String?
    public var priority: Int?
    public var remainingCents: Int?
    public var tags: String?
    public var userId: String?
    public var voided: Bool?

    public init(active: Bool? = nil, amountCents: Int? = nil, createdAt: String? = nil, currency: String? = nil, effectiveAt: String? = nil, expiresAt: String? = nil, id: String? = nil, name: String? = nil, priority: Int? = nil, remainingCents: Int? = nil, tags: String? = nil, userId: String? = nil, voided: Bool? = nil) {
        self.active = active
        self.amountCents = amountCents
        self.createdAt = createdAt
        self.currency = currency
        self.effectiveAt = effectiveAt
        self.expiresAt = expiresAt
        self.id = id
        self.name = name
        self.priority = priority
        self.remainingCents = remainingCents
        self.tags = tags
        self.userId = userId
        self.voided = voided
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case active
        case amountCents
        case createdAt
        case currency
        case effectiveAt
        case expiresAt
        case id
        case name
        case priority
        case remainingCents
        case tags
        case userId
        case voided
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(active, forKey: .active)
        try container.encodeIfPresent(amountCents, forKey: .amountCents)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(effectiveAt, forKey: .effectiveAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(remainingCents, forKey: .remainingCents)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(voided, forKey: .voided)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CreditGrant: Identifiable {}
