//
// CryptoDeposit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CryptoDeposit: Sendable, Codable, ParameterConvertible, Hashable {

    public var addressTag: String?
    public var chain: String?
    public var depositAddress: String?
    public var expiresAt: String?
    public var id: String?
    public var status: String?
    public var token: String?

    public init(addressTag: String? = nil, chain: String? = nil, depositAddress: String? = nil, expiresAt: String? = nil, id: String? = nil, status: String? = nil, token: String? = nil) {
        self.addressTag = addressTag
        self.chain = chain
        self.depositAddress = depositAddress
        self.expiresAt = expiresAt
        self.id = id
        self.status = status
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addressTag
        case chain
        case depositAddress
        case expiresAt
        case id
        case status
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addressTag, forKey: .addressTag)
        try container.encodeIfPresent(chain, forKey: .chain)
        try container.encodeIfPresent(depositAddress, forKey: .depositAddress)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(token, forKey: .token)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CryptoDeposit: Identifiable {}
