//
// DataroomDocumentOne.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DataroomDocumentOne: Sendable, Codable, ParameterConvertible, Hashable {

    /** Document is the requested document's METADATA. Its bytes are a separate read, GET /v1/dataroom/documents/{id}/file. */
    public var document: DataroomDocument?

    public init(document: DataroomDocument? = nil) {
        self.document = document
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case document
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(document, forKey: .document)
    }
}

