//
// DbGetBranch200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DbGetBranch200Response: Codable, JSONEncodable, Hashable {

    public var branch: DbBranch?

    public init(branch: DbBranch? = nil) {
        self.branch = branch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case branch
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(branch, forKey: .branch)
    }
}

