//
// DbOperation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DbOperation: Codable, JSONEncodable, Hashable {

    public enum Action: String, Codable, CaseIterable {
        case createProject = "create_project"
        case createBranch = "create_branch"
        case deleteBranch = "delete_branch"
        case createEndpoint = "create_endpoint"
        case startCompute = "start_compute"
        case suspendCompute = "suspend_compute"
        case deleteEndpoint = "delete_endpoint"
        case applyConfig = "apply_config"
        case checkAvailability = "check_availability"
        case createTimeline = "create_timeline"
        case tenantMigrate = "tenant_migrate"
    }
    public enum Status: String, Codable, CaseIterable {
        case scheduling = "scheduling"
        case running = "running"
        case finished = "finished"
        case failed = "failed"
        case cancelling = "cancelling"
        case cancelled = "cancelled"
        case skipping = "skipping"
    }
    public var id: UUID?
    public var projectId: String?
    public var branchId: String?
    public var endpointId: String?
    public var action: Action?
    public var status: Status?
    public var failuresCount: Int?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: UUID? = nil, projectId: String? = nil, branchId: String? = nil, endpointId: String? = nil, action: Action? = nil, status: Status? = nil, failuresCount: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.projectId = projectId
        self.branchId = branchId
        self.endpointId = endpointId
        self.action = action
        self.status = status
        self.failuresCount = failuresCount
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case projectId = "project_id"
        case branchId = "branch_id"
        case endpointId = "endpoint_id"
        case action
        case status
        case failuresCount = "failures_count"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(branchId, forKey: .branchId)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(failuresCount, forKey: .failuresCount)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DbOperation: Identifiable {}
