//
// DefsOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DefsOut: Sendable, Codable, ParameterConvertible, Hashable {

    /** Data is every definition in the caller's (org, project) store, by key. */
    public var data: [DefRow]?

    public init(data: [DefRow]? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

