//
// DeploymentView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeploymentView: Sendable, Codable, ParameterConvertible, Hashable {

    public var applicationId: String?
    public var buildId: String?
    public var commit: String?
    public var createdAt: Int?
    public var id: String?
    public var image: String?
    public var message: String?
    public var org: String?
    public var source: String?
    public var status: String?
    public var updatedAt: Int?
    public var version: Int?

    public init(applicationId: String? = nil, buildId: String? = nil, commit: String? = nil, createdAt: Int? = nil, id: String? = nil, image: String? = nil, message: String? = nil, org: String? = nil, source: String? = nil, status: String? = nil, updatedAt: Int? = nil, version: Int? = nil) {
        self.applicationId = applicationId
        self.buildId = buildId
        self.commit = commit
        self.createdAt = createdAt
        self.id = id
        self.image = image
        self.message = message
        self.org = org
        self.source = source
        self.status = status
        self.updatedAt = updatedAt
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applicationId
        case buildId
        case commit
        case createdAt
        case id
        case image
        case message
        case org
        case source
        case status
        case updatedAt
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(applicationId, forKey: .applicationId)
        try container.encodeIfPresent(buildId, forKey: .buildId)
        try container.encodeIfPresent(commit, forKey: .commit)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(org, forKey: .org)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(version, forKey: .version)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DeploymentView: Identifiable {}
