//
// DeployHealth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeployHealth: Sendable, Codable, ParameterConvertible, Hashable {

    /** CRD reports whether the App custom resource is served and listable. Absent when the apiserver was unreachable, because then it is unknown rather than false. */
    public var crd: Bool?
    /** K8s reports whether the Kubernetes API is reachable. Absent when the probe did not get far enough to find out. */
    public var k8s: Bool?
    /** Service names the subsystem answering, so a probe response is attributable when several are collected together. */
    public var service: String?
    /** Status is `ok` when this deployment can serve the delivery plane, and `degraded` otherwise. It agrees with the HTTP status by construction — see StatusCode. */
    public var status: String?

    public init(crd: Bool? = nil, k8s: Bool? = nil, service: String? = nil, status: String? = nil) {
        self.crd = crd
        self.k8s = k8s
        self.service = service
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case crd
        case k8s
        case service
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(crd, forKey: .crd)
        try container.encodeIfPresent(k8s, forKey: .k8s)
        try container.encodeIfPresent(service, forKey: .service)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

