//
// DnsListRecords200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DnsListRecords200Response: Codable, JSONEncodable, Hashable {

    public var records: [DnsRecord]?
    public var total: Int?

    public init(records: [DnsRecord]? = nil, total: Int? = nil) {
        self.records = records
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case records
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(records, forKey: .records)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

