//
// DocumentSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DocumentSummary: Sendable, Codable, ParameterConvertible, Hashable {

    /** Category is the template's category: formation, equity, ops or sales. */
    public var category: String?
    /** CreatedAt is when the document was generated, in unix seconds. */
    public var createdAt: Int64?
    /** EsignProvider names the e-signature provider handling it, absent until a signature has been requested. */
    public var esignProvider: String?
    /** ID is the document's server-minted handle, \"doc_\"-prefixed. */
    public var id: String?
    /** SignedAt is when the provider reported completion, in unix seconds. Absent until then. */
    public var signedAt: Int64?
    /** Status is the lifecycle state: draft, out_for_signature, signed or voided. There is deliberately no \"legally valid\" state — that is counsel's determination, not the platform's. */
    public var status: String?
    /** TemplateID is the template it was rendered from. */
    public var templateId: String?
    /** TemplateVersion is WHICH version of that template rendered it, so the document is reproducible and auditable. */
    public var templateVersion: Int64?
    /** Title is the document's title, inherited from the template. */
    public var title: String?
    /** UpdatedAt is when it last changed, in unix seconds. */
    public var updatedAt: Int64?

    public init(category: String? = nil, createdAt: Int64? = nil, esignProvider: String? = nil, id: String? = nil, signedAt: Int64? = nil, status: String? = nil, templateId: String? = nil, templateVersion: Int64? = nil, title: String? = nil, updatedAt: Int64? = nil) {
        self.category = category
        self.createdAt = createdAt
        self.esignProvider = esignProvider
        self.id = id
        self.signedAt = signedAt
        self.status = status
        self.templateId = templateId
        self.templateVersion = templateVersion
        self.title = title
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case createdAt
        case esignProvider
        case id
        case signedAt
        case status
        case templateId
        case templateVersion
        case title
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(esignProvider, forKey: .esignProvider)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(signedAt, forKey: .signedAt)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(templateId, forKey: .templateId)
        try container.encodeIfPresent(templateVersion, forKey: .templateVersion)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DocumentSummary: Identifiable {}
