//
// EnablementBoard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EnablementBoard: Sendable, Codable, ParameterConvertible, Hashable {

    /** Betas are the subset of Items the caller's org may still opt into. */
    public var betas: [UserEnablementItem]?
    /** Items is every managed item, each resolved for the caller's org. */
    public var items: [UserEnablementItem]?
    /** Org is the org this view was resolved for; empty for a caller with no validated principal, who sees only the generally-available items. */
    public var org: String?

    public init(betas: [UserEnablementItem]? = nil, items: [UserEnablementItem]? = nil, org: String? = nil) {
        self.betas = betas
        self.items = items
        self.org = org
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case betas
        case items
        case org
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(betas, forKey: .betas)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(org, forKey: .org)
    }
}

