//
// EnvVarJSON.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EnvVarJSON: Sendable, Codable, ParameterConvertible, Hashable {

    public var key: String?
    public var secret: Bool?
    public var value: String?

    public init(key: String? = nil, secret: Bool? = nil, value: String? = nil) {
        self.key = key
        self.secret = secret
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case secret
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

