//
// FilesJSON.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FilesJSON: Sendable, Codable, ParameterConvertible, Hashable {

    /** Files are the selected files, sorted by path. Directories are never returned. */
    public var files: [FileJSON]?
    /** Rev is the full revision the ref resolved to — pin follow-up reads to it. */
    public var rev: String?

    public init(files: [FileJSON]? = nil, rev: String? = nil) {
        self.files = files
        self.rev = rev
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case files
        case rev
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(files, forKey: .files)
        try container.encodeIfPresent(rev, forKey: .rev)
    }
}

