//
// Filing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Filing: Sendable, Codable, ParameterConvertible, Hashable {

    /** At is the unix second the filing record was written. */
    public var at: Int?
    /** Note explains a filing Hanzo did not perform itself: what remains to be done and by whom. */
    public var note: String?
    /** Provider is the filing partner that performed the filing, or \"manual\" when no partner is wired. */
    public var provider: String?
    /** Ref is the partner's or the state's filing reference. Empty when nothing was actually filed — no filing id is ever fabricated. */
    public var ref: String?
    /** Status is manual (no partner wired — a registered agent files out-of-band), submitted (the partner accepted it, awaiting the state), filed (the state accepted it) or rejected. */
    public var status: String?

    public init(at: Int? = nil, note: String? = nil, provider: String? = nil, ref: String? = nil, status: String? = nil) {
        self.at = at
        self.note = note
        self.provider = provider
        self.ref = ref
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case at
        case note
        case provider
        case ref
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(at, forKey: .at)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(ref, forKey: .ref)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

