//
// FleetSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FleetSpec: Sendable, Codable, ParameterConvertible, Hashable {

    public var arch: String?
    public var cpus: Int?
    public var gpuModel: String?
    public var gpus: Int?
    public var memory: Int?
    public var os: String?

    public init(arch: String? = nil, cpus: Int? = nil, gpuModel: String? = nil, gpus: Int? = nil, memory: Int? = nil, os: String? = nil) {
        self.arch = arch
        self.cpus = cpus
        self.gpuModel = gpuModel
        self.gpus = gpus
        self.memory = memory
        self.os = os
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case arch
        case cpus
        case gpuModel
        case gpus
        case memory
        case os
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(arch, forKey: .arch)
        try container.encodeIfPresent(cpus, forKey: .cpus)
        try container.encodeIfPresent(gpuModel, forKey: .gpuModel)
        try container.encodeIfPresent(gpus, forKey: .gpus)
        try container.encodeIfPresent(memory, forKey: .memory)
        try container.encodeIfPresent(os, forKey: .os)
    }
}

