//
// FnList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FnList: Sendable, Codable, ParameterConvertible, Hashable {

    /** Functions is one row per published function. */
    public var functions: [FunctionView]?

    public init(functions: [FunctionView]? = nil) {
        self.functions = functions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case functions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(functions, forKey: .functions)
    }
}

