//
// Formation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Formation: Sendable, Codable, ParameterConvertible, Hashable {

    /** AlreadyIncorporated declares an org that already has a legal entity, which takes the import path (structure → import → company) instead of forming one. */
    public var alreadyIncorporated: Bool?
    /** CapTableImported reports whether the existing company's cap table has been imported onto the canonical cap table. */
    public var capTableImported: Bool?
    /** CreatedAt is the unix second the formation was opened. */
    public var createdAt: Int64?
    /** DocumentIDs are the data room ids of the GENERATED formation documents. */
    public var documentIds: [String]?
    /** EsignRef is the e-signature provider's reference for the signature request. */
    public var esignRef: String?
    /** Filing is the state-of-incorporation filing record, once documents exist. */
    public var filing: Filing?
    /** Founders is every founding stakeholder, with its equity split and KYC state. */
    public var founders: [Founder]?
    /** Genesis is the cap-table equity genesis, once recorded. */
    public var genesis: Genesis?
    /** Imported reports whether the existing company's corporate documents have been ingested into the org's data room. */
    public var imported: Bool?
    /** ImportedDocs are the data room ids of the documents ingested from Drive. */
    public var importedDocs: [String]?
    /** Jurisdiction is the state of formation: DE or WY. */
    public var jurisdiction: String?
    /** Name is the company name the entity is being formed under. */
    public var name: String?
    /** Org is the owning org — the tenant key, and the reason there is exactly one formation per org. */
    public var org: String?
    /** Paid reports whether the one-time formation fee has been charged. */
    public var paid: Bool?
    /** PaymentRef is the billing reference recorded for the charged formation fee on the org's own ledger. */
    public var paymentRef: String?
    /** Signed reports whether the formation documents have come back signed — the e-signature provider's answer, which a real provider's webhook drives. */
    public var signed: Bool?
    /** Stage is the machine's current state: structure, founders, payment, documents, esign or genesis on the formation path, import on the skip path, and company at the terminal. */
    public var stage: String?
    /** Structure is the legal entity being formed: c-corp, llc or dao-llc. */
    public var structure: String?
    /** UpdatedAt is the unix second of the most recent write to the formation. */
    public var updatedAt: Int64?

    public init(alreadyIncorporated: Bool? = nil, capTableImported: Bool? = nil, createdAt: Int64? = nil, documentIds: [String]? = nil, esignRef: String? = nil, filing: Filing? = nil, founders: [Founder]? = nil, genesis: Genesis? = nil, imported: Bool? = nil, importedDocs: [String]? = nil, jurisdiction: String? = nil, name: String? = nil, org: String? = nil, paid: Bool? = nil, paymentRef: String? = nil, signed: Bool? = nil, stage: String? = nil, structure: String? = nil, updatedAt: Int64? = nil) {
        self.alreadyIncorporated = alreadyIncorporated
        self.capTableImported = capTableImported
        self.createdAt = createdAt
        self.documentIds = documentIds
        self.esignRef = esignRef
        self.filing = filing
        self.founders = founders
        self.genesis = genesis
        self.imported = imported
        self.importedDocs = importedDocs
        self.jurisdiction = jurisdiction
        self.name = name
        self.org = org
        self.paid = paid
        self.paymentRef = paymentRef
        self.signed = signed
        self.stage = stage
        self.structure = structure
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alreadyIncorporated
        case capTableImported
        case createdAt
        case documentIds
        case esignRef
        case filing
        case founders
        case genesis
        case imported
        case importedDocs
        case jurisdiction
        case name
        case org
        case paid
        case paymentRef
        case signed
        case stage
        case structure
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alreadyIncorporated, forKey: .alreadyIncorporated)
        try container.encodeIfPresent(capTableImported, forKey: .capTableImported)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(documentIds, forKey: .documentIds)
        try container.encodeIfPresent(esignRef, forKey: .esignRef)
        try container.encodeIfPresent(filing, forKey: .filing)
        try container.encodeIfPresent(founders, forKey: .founders)
        try container.encodeIfPresent(genesis, forKey: .genesis)
        try container.encodeIfPresent(imported, forKey: .imported)
        try container.encodeIfPresent(importedDocs, forKey: .importedDocs)
        try container.encodeIfPresent(jurisdiction, forKey: .jurisdiction)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(org, forKey: .org)
        try container.encodeIfPresent(paid, forKey: .paid)
        try container.encodeIfPresent(paymentRef, forKey: .paymentRef)
        try container.encodeIfPresent(signed, forKey: .signed)
        try container.encodeIfPresent(stage, forKey: .stage)
        try container.encodeIfPresent(structure, forKey: .structure)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

