//
// Frame.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Frame: Sendable, Codable, ParameterConvertible, Hashable {

    public var column: Int?
    public var file: String?
    public var function: String?
    public var line: Int?

    public init(column: Int? = nil, file: String? = nil, function: String? = nil, line: Int? = nil) {
        self.column = column
        self.file = file
        self.function = function
        self.line = line
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case column
        case file
        case function
        case line
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(column, forKey: .column)
        try container.encodeIfPresent(file, forKey: .file)
        try container.encodeIfPresent(function, forKey: .function)
        try container.encodeIfPresent(line, forKey: .line)
    }
}

