//
// Genesis.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Genesis: Sendable, Codable, ParameterConvertible, Hashable {

    /** At is the unix second the genesis root was computed. */
    public var at: Int64?
    /** Block is the L1 block the anchoring transaction landed in. Set only once the receipt has been read; absent otherwise. */
    public var block: Int?
    /** ChainID is the EVM chain the root is committed to — the Hanzo L1 by default. */
    public var chainId: Int64?
    /** Note explains an unanchored genesis honestly — anchor wiring absent, or the submit error — rather than reporting a commit that did not happen. */
    public var note: String?
    /** Root is the 0x-prefixed keccak256 root of the founding allocation. It is ALWAYS computed, whether or not the on-chain anchor is wired, because the root is the tamper-evident witness. */
    public var root: String?
    /** Status is pending (root computed, not yet on-chain) or anchored (committed). */
    public var status: String?
    /** TxHash is the L1 transaction hash of the anchoring commit. Empty until anchored. */
    public var txHash: String?

    public init(at: Int64? = nil, block: Int? = nil, chainId: Int64? = nil, note: String? = nil, root: String? = nil, status: String? = nil, txHash: String? = nil) {
        self.at = at
        self.block = block
        self.chainId = chainId
        self.note = note
        self.root = root
        self.status = status
        self.txHash = txHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case at
        case block
        case chainId
        case note
        case root
        case status
        case txHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(at, forKey: .at)
        try container.encodeIfPresent(block, forKey: .block)
        try container.encodeIfPresent(chainId, forKey: .chainId)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(root, forKey: .root)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(txHash, forKey: .txHash)
    }
}

