//
// GithubForkOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GithubForkOut: Sendable, Codable, ParameterConvertible, Hashable {

    public var cloneUrl: String?
    public var defaultBranch: String?
    /** Existing reports that the fork was already there. GitHub answers 202 either way, so without this a caller cannot tell \"made you one\" from \"you had one\". */
    public var existing: Bool?
    public var fullName: String?
    public var htmlUrl: String?

    public init(cloneUrl: String? = nil, defaultBranch: String? = nil, existing: Bool? = nil, fullName: String? = nil, htmlUrl: String? = nil) {
        self.cloneUrl = cloneUrl
        self.defaultBranch = defaultBranch
        self.existing = existing
        self.fullName = fullName
        self.htmlUrl = htmlUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cloneUrl = "clone_url"
        case defaultBranch = "default_branch"
        case existing
        case fullName = "full_name"
        case htmlUrl = "html_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cloneUrl, forKey: .cloneUrl)
        try container.encodeIfPresent(defaultBranch, forKey: .defaultBranch)
        try container.encodeIfPresent(existing, forKey: .existing)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(htmlUrl, forKey: .htmlUrl)
    }
}

