//
// GraphVocabularyOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GraphVocabularyOut: Sendable, Codable, ParameterConvertible, Hashable {

    /** Bound is the ceiling on one walk. */
    public var bound: Int?
    /** Relations is what this organization has actually asserted, which is the only vocabulary there is: this plane declares none of its own. */
    public var relations: [String]?
    /** Rule names the terms of the precedence order, in the order they apply. A reader who is told a winner without the rule cannot check it. */
    public var rule: [String]?

    public init(bound: Int? = nil, relations: [String]? = nil, rule: [String]? = nil) {
        self.bound = bound
        self.relations = relations
        self.rule = rule
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bound
        case relations
        case rule
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bound, forKey: .bound)
        try container.encodeIfPresent(relations, forKey: .relations)
        try container.encodeIfPresent(rule, forKey: .rule)
    }
}

