//
// History.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct History: Sendable, Codable, ParameterConvertible, Hashable {

    /** At is the token this is the history of, lowercased. */
    public var at: String?
    public var chain: String?
    /** Days is oldest first, which is the order a chart draws. `[]` for a token the indexer holds no day for, `null` where the read failed. */
    public var days: [Day]?
    public var reach: Reach?

    public init(at: String? = nil, chain: String? = nil, days: [Day]? = nil, reach: Reach? = nil) {
        self.at = at
        self.chain = chain
        self.days = days
        self.reach = reach
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case at
        case chain
        case days
        case reach
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(at, forKey: .at)
        try container.encodeIfPresent(chain, forKey: .chain)
        try container.encodeIfPresent(days, forKey: .days)
        try container.encodeIfPresent(reach, forKey: .reach)
    }
}

