//
// IamControllersLaravelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IamControllersLaravelResponse: Codable, JSONEncodable, Hashable {

    public var createdAt: String?
    public var email: String?
    public var emailVerifiedAt: String?
    public var id: String?
    public var name: String?
    public var updatedAt: String?

    public init(createdAt: String? = nil, email: String? = nil, emailVerifiedAt: String? = nil, id: String? = nil, name: String? = nil, updatedAt: String? = nil) {
        self.createdAt = createdAt
        self.email = email
        self.emailVerifiedAt = emailVerifiedAt
        self.id = id
        self.name = name
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case email
        case emailVerifiedAt = "email_verified_at"
        case id
        case name
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(emailVerifiedAt, forKey: .emailVerifiedAt)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension IamControllersLaravelResponse: Identifiable {}
