//
// IamFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IamFilter: Sendable, Codable, ParameterConvertible, Hashable {

    public var maxResults: Int?
    public var supported: Bool?

    public init(maxResults: Int? = nil, supported: Bool? = nil) {
        self.maxResults = maxResults
        self.supported = supported
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxResults
        case supported
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxResults, forKey: .maxResults)
        try container.encodeIfPresent(supported, forKey: .supported)
    }
}

