//
// IamObjectTransactionCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IamObjectTransactionCategory: String, Codable, CaseIterable {
    case transactioncategorypurchaseEqualDoubleQuotePurchaseDoubleQuote = "TransactionCategoryPurchase = "Purchase""
    case transactioncategoryrechargeEqualDoubleQuoteRechargeDoubleQuote = "TransactionCategoryRecharge = "Recharge""
}
