//
// IndexList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IndexList: Sendable, Codable, ParameterConvertible, Hashable {

    /** Limit is how many rows this page could hold. */
    public var limit: Int?
    /** Offset is where this page starts. */
    public var offset: Int?
    /** Results are the index definitions themselves. */
    public var results: [IndexView]?
    /** Total is how many indexes the org holds altogether. */
    public var total: Int?

    public init(limit: Int? = nil, offset: Int? = nil, results: [IndexView]? = nil, total: Int? = nil) {
        self.limit = limit
        self.offset = offset
        self.results = results
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limit
        case offset
        case results
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(results, forKey: .results)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

