//
// IssueEdit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IssueEdit: Sendable, Codable, ParameterConvertible, Hashable {

    /** Description rewrites the body. */
    public var description: String?
    /** Key is the board — the repository name, from the path. */
    public var key: String?
    /** Num is the issue number on that repository, from the path. */
    public var num: Int?
    /** Priority re-prioritises it. */
    public var priority: String?
    /** Status moves the card to another column. */
    public var status: String?
    /** Title renames the work item. */
    public var title: String?

    public init(description: String? = nil, key: String? = nil, num: Int? = nil, priority: String? = nil, status: String? = nil, title: String? = nil) {
        self.description = description
        self.key = key
        self.num = num
        self.priority = priority
        self.status = status
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case key
        case num
        case priority
        case status
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(num, forKey: .num)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

