//
// KmsCreateSsoConfigRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KmsCreateSsoConfigRequest: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case saml = "saml"
        case oidc = "oidc"
    }
    public var orgId: UUID
    public var type: ModelType
    public var isActive: Bool? = true

    public init(orgId: UUID, type: ModelType, isActive: Bool? = true) {
        self.orgId = orgId
        self.type = type
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orgId
        case type
        case isActive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orgId, forKey: .orgId)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(isActive, forKey: .isActive)
    }
}

