//
// KmsIssueCertificate200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KmsIssueCertificate200Response: Codable, JSONEncodable, Hashable {

    /** PEM-encoded certificate */
    public var certificate: String?
    /** PEM-encoded certificate chain */
    public var certificateChain: String?
    /** PEM-encoded private key */
    public var privateKey: String?
    public var serialNumber: String?

    public init(certificate: String? = nil, certificateChain: String? = nil, privateKey: String? = nil, serialNumber: String? = nil) {
        self.certificate = certificate
        self.certificateChain = certificateChain
        self.privateKey = privateKey
        self.serialNumber = serialNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case certificate
        case certificateChain
        case privateKey
        case serialNumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(certificate, forKey: .certificate)
        try container.encodeIfPresent(certificateChain, forKey: .certificateChain)
        try container.encodeIfPresent(privateKey, forKey: .privateKey)
        try container.encodeIfPresent(serialNumber, forKey: .serialNumber)
    }
}

