//
// KmsListSharedSecrets200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KmsListSharedSecrets200Response: Codable, JSONEncodable, Hashable {

    public var secrets: [KmsSharedSecret]?

    public init(secrets: [KmsSharedSecret]? = nil) {
        self.secrets = secrets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case secrets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(secrets, forKey: .secrets)
    }
}

