//
// KmsSdkEnvelopeIdentity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The mnemonic-derived service identity block. Bound into the signature. */
public struct KmsSdkEnvelopeIdentity: Codable, JSONEncodable, Hashable {

    /** NodeID scheme. 0x42 = ML-DSA-65. */
    public var scheme: Int
    /** 20-byte canonical NodeID (cb58), the SHAKE256-384 digest prefix. */
    public var node: String
    /** 48-byte SHAKE256-384 FullDigest commitment (base64). */
    public var digest: Data
    /** BIP-44 service path the identity was derived from (e.g. hanzo/kms-operator). */
    public var path: String
    /** ML-DSA-65 public key (base64), for offline verification. */
    public var pubkey: Data

    public init(scheme: Int, node: String, digest: Data, path: String, pubkey: Data) {
        self.scheme = scheme
        self.node = node
        self.digest = digest
        self.path = path
        self.pubkey = pubkey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case scheme
        case node
        case digest
        case path
        case pubkey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(scheme, forKey: .scheme)
        try container.encode(node, forKey: .node)
        try container.encode(digest, forKey: .digest)
        try container.encode(path, forKey: .path)
        try container.encode(pubkey, forKey: .pubkey)
    }
}

