//
// KmsUpdateIntegrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KmsUpdateIntegrationRequest: Codable, JSONEncodable, Hashable {

    public var app: String?
    public var isActive: Bool?
    public var targetEnvironment: String?

    public init(app: String? = nil, isActive: Bool? = nil, targetEnvironment: String? = nil) {
        self.app = app
        self.isActive = isActive
        self.targetEnvironment = targetEnvironment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case isActive
        case targetEnvironment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(targetEnvironment, forKey: .targetEnvironment)
    }
}

