//
// KmsWebhook.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KmsWebhook: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var url: String?
    public var envId: UUID?
    public var secretPath: String?
    public var isDisabled: Bool?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: UUID? = nil, url: String? = nil, envId: UUID? = nil, secretPath: String? = nil, isDisabled: Bool? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.url = url
        self.envId = envId
        self.secretPath = secretPath
        self.isDisabled = isDisabled
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case envId
        case secretPath
        case isDisabled
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(envId, forKey: .envId)
        try container.encodeIfPresent(secretPath, forKey: .secretPath)
        try container.encodeIfPresent(isDisabled, forKey: .isDisabled)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension KmsWebhook: Identifiable {}
