//
// KvClusterNodesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KvClusterNodesInner: Codable, JSONEncodable, Hashable {

    public enum Role: String, Codable, CaseIterable {
        case primary = "primary"
        case replica = "replica"
    }
    public enum Status: String, Codable, CaseIterable {
        case online = "online"
        case offline = "offline"
        case syncing = "syncing"
    }
    public var id: String?
    public var role: Role?
    public var host: String?
    public var port: Int?
    public var status: Status?
    public var memoryUsedMb: Double?
    public var memoryMaxMb: Int?

    public init(id: String? = nil, role: Role? = nil, host: String? = nil, port: Int? = nil, status: Status? = nil, memoryUsedMb: Double? = nil, memoryMaxMb: Int? = nil) {
        self.id = id
        self.role = role
        self.host = host
        self.port = port
        self.status = status
        self.memoryUsedMb = memoryUsedMb
        self.memoryMaxMb = memoryMaxMb
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case role
        case host
        case port
        case status
        case memoryUsedMb = "memory_used_mb"
        case memoryMaxMb = "memory_max_mb"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(host, forKey: .host)
        try container.encodeIfPresent(port, forKey: .port)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(memoryUsedMb, forKey: .memoryUsedMb)
        try container.encodeIfPresent(memoryMaxMb, forKey: .memoryMaxMb)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension KvClusterNodesInner: Identifiable {}
