//
// LeaseIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LeaseIn: Sendable, Codable, ParameterConvertible, Hashable {

    /** Class is what KIND of computer to lease, and the set is closed:   exec     a throwaway one that keeps nothing. Seconds to minutes.  dev      a coding one, with the project's own disk attached. Hours.  desktop  a dev one that also has a screen.  android  a desktop with a phone running on that screen.  Empty leases an `exec`, which is the right answer for running a program and the wrong one for working on a repository, because it keeps nothing.  An `android` needs a node that can virtualise a CPU, so it is the one class a deployment may not be able to place. Where the fleet has none, the lease succeeds and the pod stays Pending naming the device it is waiting for — which is the honest answer, because the alternative is an emulator running on an interpreted CPU and never finishing its boot. */
    public var _class: String?
    /** ID names a sandbox to RESUME, and is the id an earlier lease answered with. Empty asks for a new one. A caller that holds an id and omits it does not get a second view of the same computer, it gets a second computer. */
    public var id: String?
    /** Project names the disk to attach, and is REQUIRED for every class but `exec`.  One live sandbox per project: the disk attaches to one computer at a time, so a second lease over a project that already has one is refused by name rather than handed a silently empty disk. */
    public var project: String?
    /** Runtime is the isolation boundary asked for: `gvisor` shares a filesystem and holds a project volume, `kata-fc` is a microVM that boots slower and reads files faster but has no shared filesystem at all. Empty asks for the fleet's default, which is the right answer unless you are measuring.  It is a REQUEST. The owner decides, and refuses a combination it cannot honour — a volume under a runtime with no shared filesystem would write into a tmpfs and lose the bytes at exit. Read Leased.Runtime for what the sandbox actually got. */
    public var runtime: String?
    /** TTLSec bounds the lease in seconds. Unset takes the class default. Nothing runs forever, because a sandbox is somebody else's code on our nodes. */
    public var ttlSec: Int?

    public init(_class: String? = nil, id: String? = nil, project: String? = nil, runtime: String? = nil, ttlSec: Int? = nil) {
        self._class = _class
        self.id = id
        self.project = project
        self.runtime = runtime
        self.ttlSec = ttlSec
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _class = "class"
        case id
        case project
        case runtime
        case ttlSec
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_class, forKey: ._class)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(project, forKey: .project)
        try container.encodeIfPresent(runtime, forKey: .runtime)
        try container.encodeIfPresent(ttlSec, forKey: .ttlSec)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension LeaseIn: Identifiable {}
