//
// LLMOverview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LLMOverview: Sendable, Codable, ParameterConvertible, Hashable {

    /** Available is true whenever the ledger answered — including with no usage in the window, which is honest zeros rather than a missing lens. */
    public var available: Bool?
    /** CompletionTokens is the output half of Tokens. */
    public var completionTokens: Int?
    /** ErrorRate is Errors/Requests, 0..1, rounded to three places. Zero when there were no requests. */
    public var errorRate: Double?
    /** Errors is how many of Requests failed. */
    public var errors: Int?
    /** Models is how many distinct models the org called. */
    public var models: Int?
    /** PromptTokens is the input half of Tokens. */
    public var promptTokens: Int?
    /** Providers is how many distinct providers served them. */
    public var providers: Int?
    /** Requests is how many LLM calls the org made in the window. */
    public var requests: Int?
    /** Source is the warehouse table the lens read. */
    public var source: String?
    /** SpendCents is what those calls cost, in cents. */
    public var spendCents: Int?
    /** Tokens is prompt plus completion tokens over those calls. */
    public var tokens: Int?

    public init(available: Bool? = nil, completionTokens: Int? = nil, errorRate: Double? = nil, errors: Int? = nil, models: Int? = nil, promptTokens: Int? = nil, providers: Int? = nil, requests: Int? = nil, source: String? = nil, spendCents: Int? = nil, tokens: Int? = nil) {
        self.available = available
        self.completionTokens = completionTokens
        self.errorRate = errorRate
        self.errors = errors
        self.models = models
        self.promptTokens = promptTokens
        self.providers = providers
        self.requests = requests
        self.source = source
        self.spendCents = spendCents
        self.tokens = tokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case available
        case completionTokens
        case errorRate
        case errors
        case models
        case promptTokens
        case providers
        case requests
        case source
        case spendCents
        case tokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(available, forKey: .available)
        try container.encodeIfPresent(completionTokens, forKey: .completionTokens)
        try container.encodeIfPresent(errorRate, forKey: .errorRate)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(models, forKey: .models)
        try container.encodeIfPresent(promptTokens, forKey: .promptTokens)
        try container.encodeIfPresent(providers, forKey: .providers)
        try container.encodeIfPresent(requests, forKey: .requests)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(spendCents, forKey: .spendCents)
        try container.encodeIfPresent(tokens, forKey: .tokens)
    }
}

