//
// McpServerList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct McpServerList: Sendable, Codable, ParameterConvertible, Hashable {

    /** Servers is every external MCP server this org has registered. No secret VALUE is ever included — only whether one is set. */
    public var servers: [MCPServer]?

    public init(servers: [MCPServer]? = nil) {
        self.servers = servers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case servers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(servers, forKey: .servers)
    }
}

