//
// MetricsData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MetricsData: Sendable, Codable, ParameterConvertible, Hashable {

    public var asOf: String?
    public var currency: String?
    public var customers: [SaaSCustomer]?
    public var gaps: [String]?
    public var generatedAt: String?
    public var orgs: Int?
    public var revenue: SaaSRevenue?
    public var sources: [SourceStatus]?
    public var subscriptions: SaaSSubs?
    public var usage: SaaSUsage?
    public var window: String?

    public init(asOf: String? = nil, currency: String? = nil, customers: [SaaSCustomer]? = nil, gaps: [String]? = nil, generatedAt: String? = nil, orgs: Int? = nil, revenue: SaaSRevenue? = nil, sources: [SourceStatus]? = nil, subscriptions: SaaSSubs? = nil, usage: SaaSUsage? = nil, window: String? = nil) {
        self.asOf = asOf
        self.currency = currency
        self.customers = customers
        self.gaps = gaps
        self.generatedAt = generatedAt
        self.orgs = orgs
        self.revenue = revenue
        self.sources = sources
        self.subscriptions = subscriptions
        self.usage = usage
        self.window = window
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case asOf
        case currency
        case customers
        case gaps
        case generatedAt
        case orgs
        case revenue
        case sources
        case subscriptions
        case usage
        case window
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(asOf, forKey: .asOf)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(customers, forKey: .customers)
        try container.encodeIfPresent(gaps, forKey: .gaps)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
        try container.encodeIfPresent(orgs, forKey: .orgs)
        try container.encodeIfPresent(revenue, forKey: .revenue)
        try container.encodeIfPresent(sources, forKey: .sources)
        try container.encodeIfPresent(subscriptions, forKey: .subscriptions)
        try container.encodeIfPresent(usage, forKey: .usage)
        try container.encodeIfPresent(window, forKey: .window)
    }
}

