//
// MlListExperiments200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MlListExperiments200Response: Codable, JSONEncodable, Hashable {

    public var experiments: [MlExperiment]?

    public init(experiments: [MlExperiment]? = nil) {
        self.experiments = experiments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case experiments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(experiments, forKey: .experiments)
    }
}

