//
// MoneyBoard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MoneyBoard: Sendable, Codable, ParameterConvertible, Hashable {

    public var byOrg: [MoneyOrgRow]?
    public var credits: MoneyCredits?
    public var generatedAt: String?
    public var infrastructure: MoneyInfra?
    public var margin: MoneyMargin?
    public var revenue: MoneyRevenue?
    public var sources: [SourceStatus]?

    public init(byOrg: [MoneyOrgRow]? = nil, credits: MoneyCredits? = nil, generatedAt: String? = nil, infrastructure: MoneyInfra? = nil, margin: MoneyMargin? = nil, revenue: MoneyRevenue? = nil, sources: [SourceStatus]? = nil) {
        self.byOrg = byOrg
        self.credits = credits
        self.generatedAt = generatedAt
        self.infrastructure = infrastructure
        self.margin = margin
        self.revenue = revenue
        self.sources = sources
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case byOrg
        case credits
        case generatedAt
        case infrastructure
        case margin
        case revenue
        case sources
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(byOrg, forKey: .byOrg)
        try container.encodeIfPresent(credits, forKey: .credits)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
        try container.encodeIfPresent(infrastructure, forKey: .infrastructure)
        try container.encodeIfPresent(margin, forKey: .margin)
        try container.encodeIfPresent(revenue, forKey: .revenue)
        try container.encodeIfPresent(sources, forKey: .sources)
    }
}

