//
// MqListStreams200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MqListStreams200Response: Codable, JSONEncodable, Hashable {

    public var streams: [MqStream]?
    public var total: Int?

    public init(streams: [MqStream]? = nil, total: Int? = nil) {
        self.streams = streams
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case streams
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(streams, forKey: .streams)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

