//
// MqMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A message received from a subject subscription. */
public struct MqMessage: Codable, JSONEncodable, Hashable {

    /** Subject the message was published to. */
    public var subject: String?
    /** Message payload (base64-encoded for binary data). */
    public var data: String?
    /** Message headers (key to list of values). */
    public var headers: [String: [String]]?
    /** Reply-to subject for request/reply patterns. */
    public var reply: String?
    /** Server timestamp when the message was received. */
    public var timestamp: Date?
    /** Stream sequence number (present only for JetStream messages).  */
    public var sequence: Int?

    public init(subject: String? = nil, data: String? = nil, headers: [String: [String]]? = nil, reply: String? = nil, timestamp: Date? = nil, sequence: Int? = nil) {
        self.subject = subject
        self.data = data
        self.headers = headers
        self.reply = reply
        self.timestamp = timestamp
        self.sequence = sequence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subject
        case data
        case headers
        case reply
        case timestamp
        case sequence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(headers, forKey: .headers)
        try container.encodeIfPresent(reply, forKey: .reply)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(sequence, forKey: .sequence)
    }
}

