//
// MqStreamMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A message stored in a JetStream stream. */
public struct MqStreamMessage: Codable, JSONEncodable, Hashable {

    public var subject: String?
    public var data: String?
    public var headers: [String: [String]]?
    /** Stream sequence number. */
    public var sequence: Int?
    public var timestamp: Date?
    /** Number of times this message has been delivered. */
    public var numDelivered: Int?
    /** Messages remaining after this one (consumer context). */
    public var numPending: Int?

    public init(subject: String? = nil, data: String? = nil, headers: [String: [String]]? = nil, sequence: Int? = nil, timestamp: Date? = nil, numDelivered: Int? = nil, numPending: Int? = nil) {
        self.subject = subject
        self.data = data
        self.headers = headers
        self.sequence = sequence
        self.timestamp = timestamp
        self.numDelivered = numDelivered
        self.numPending = numPending
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subject
        case data
        case headers
        case sequence
        case timestamp
        case numDelivered = "num_delivered"
        case numPending = "num_pending"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(headers, forKey: .headers)
        try container.encodeIfPresent(sequence, forKey: .sequence)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(numDelivered, forKey: .numDelivered)
        try container.encodeIfPresent(numPending, forKey: .numPending)
    }
}

