//
// O11yO11yLLMScore.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yLLMScore: Sendable, Codable, ParameterConvertible, Hashable {

    /** Comment is a free-text note. */
    public var comment: String?
    /** CreatedAt is when the score was stored. */
    public var createdAt: Date?
    /** CreatedBy is who created the score. */
    public var createdBy: String?
    /** DataType is the score's kind — NUMERIC or CATEGORICAL. */
    public var dataType: String?
    /** ID is the score's id. */
    public var id: String?
    /** Name is the score's name. */
    public var name: String?
    /** ObservationID is the observation the score attaches to, when narrowed. */
    public var observationId: String?
    /** Source is where the score came from, e.g. API, EVAL. */
    public var source: String?
    /** StringValue is the categorical score, when the score is categorical. */
    public var stringValue: String?
    /** Timestamp is the score's own event time. */
    public var timestamp: Date?
    /** TraceID is the trace the score attaches to. */
    public var traceId: String?
    /** UpdatedAt is when the score last changed. */
    public var updatedAt: Date?
    /** Value is the numeric score. */
    public var value: Double?

    public init(comment: String? = nil, createdAt: Date? = nil, createdBy: String? = nil, dataType: String? = nil, id: String? = nil, name: String? = nil, observationId: String? = nil, source: String? = nil, stringValue: String? = nil, timestamp: Date? = nil, traceId: String? = nil, updatedAt: Date? = nil, value: Double? = nil) {
        self.comment = comment
        self.createdAt = createdAt
        self.createdBy = createdBy
        self.dataType = dataType
        self.id = id
        self.name = name
        self.observationId = observationId
        self.source = source
        self.stringValue = stringValue
        self.timestamp = timestamp
        self.traceId = traceId
        self.updatedAt = updatedAt
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
        case createdAt
        case createdBy
        case dataType
        case id
        case name
        case observationId
        case source
        case stringValue
        case timestamp
        case traceId
        case updatedAt
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(dataType, forKey: .dataType)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(observationId, forKey: .observationId)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(stringValue, forKey: .stringValue)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(traceId, forKey: .traceId)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(value, forKey: .value)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension O11yO11yLLMScore: Identifiable {}
