//
// O11yO11yLogPromotePath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yLogPromotePath: Sendable, Codable, ParameterConvertible, Hashable {

    /** Indexes are the indexes to put on the path. */
    public var indexes: [O11yO11yLogPromoteIndex]?
    /** Path is the body path, e.g. body.user.id on the way in; listed without the body. prefix. */
    public var path: String?
    /** Promote lifts the path into its own column when true. */
    public var promote: Bool?

    public init(indexes: [O11yO11yLogPromoteIndex]? = nil, path: String? = nil, promote: Bool? = nil) {
        self.indexes = indexes
        self.path = path
        self.promote = promote
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case indexes
        case path
        case promote
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(indexes, forKey: .indexes)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(promote, forKey: .promote)
    }
}

