//
// O11yAvailabilityResponseRange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Range is the window and bucket width actually used, after clamping — not what was asked for, which is why a caller reads it back rather than assuming. */
public struct O11yAvailabilityResponseRange: Sendable, Codable, ParameterConvertible, Hashable {

    public var sinceSec: Int64?
    public var stepSec: Int64?

    public init(sinceSec: Int64? = nil, stepSec: Int64? = nil) {
        self.sinceSec = sinceSec
        self.stepSec = stepSec
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sinceSec
        case stepSec
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sinceSec, forKey: .sinceSec)
        try container.encodeIfPresent(stepSec, forKey: .stepSec)
    }
}

