//
// O11yO11yMetricLabel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yMetricLabel: Sendable, Codable, ParameterConvertible, Hashable {

    /** Key is the label's field. */
    public var key: O11yO11yMetricField?
    /** Value is the label's value. */
    public var value: JSONValue?

    public init(key: O11yO11yMetricField? = nil, value: JSONValue? = nil) {
        self.key = key
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

