//
// O11yO11yDomainGroupBy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yDomainGroupBy: Sendable, Codable, ParameterConvertible, Hashable {

    /** Description describes the field, when known. */
    public var description: String?
    /** FieldContext says which plane the field lives on, e.g. attribute, resource, span. */
    public var fieldContext: String?
    /** FieldDataType is the field's type: string, int64, float64 or bool. */
    public var fieldDataType: String?
    /** Name is the field's name. Required. */
    public var name: String?
    /** Signal is the telemetry signal the field belongs to, e.g. traces. */
    public var signal: String?
    /** Unit is the field's unit, when known. */
    public var unit: String?

    public init(description: String? = nil, fieldContext: String? = nil, fieldDataType: String? = nil, name: String? = nil, signal: String? = nil, unit: String? = nil) {
        self.description = description
        self.fieldContext = fieldContext
        self.fieldDataType = fieldDataType
        self.name = name
        self.signal = signal
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case fieldContext
        case fieldDataType
        case name
        case signal
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(fieldContext, forKey: .fieldContext)
        try container.encodeIfPresent(fieldDataType, forKey: .fieldDataType)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(signal, forKey: .signal)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

