//
// O11yO11yMetricOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yMetricOrder: Sendable, Codable, ParameterConvertible, Hashable {

    /** Direction is asc or desc. */
    public var direction: String?
    /** Key is the field to order by. */
    public var key: O11yO11yMetricField?

    public init(direction: String? = nil, key: O11yO11yMetricField? = nil) {
        self.direction = direction
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case direction
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(direction, forKey: .direction)
        try container.encodeIfPresent(key, forKey: .key)
    }
}

