//
// O11yMattermostField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yMattermostField: Sendable, Codable, ParameterConvertible, Hashable {

    public var short: Bool?
    public var title: String?
    public var value: String?

    public init(short: Bool? = nil, title: String? = nil, value: String? = nil) {
        self.short = short
        self.title = title
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case short
        case title
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(short, forKey: .short)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

