//
// O11yGettableTestRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yGettableTestRule: Sendable, Codable, ParameterConvertible, Hashable {

    public var alertCount: Int?
    public var message: String?

    public init(alertCount: Int? = nil, message: String? = nil) {
        self.alertCount = alertCount
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alertCount
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alertCount, forKey: .alertCount)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

