//
// O11yOldAWSMetricsStrategyCloudwatchMetricStreamFiltersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yOldAWSMetricsStrategyCloudwatchMetricStreamFiltersInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var metricNames: [String]?
    public var namespace: String?

    public init(metricNames: [String]? = nil, namespace: String? = nil) {
        self.metricNames = metricNames
        self.namespace = namespace
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metricNames = "MetricNames"
        case namespace = "Namespace"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metricNames, forKey: .metricNames)
        try container.encodeIfPresent(namespace, forKey: .namespace)
    }
}

