//
// O11yO11yMetricStatsIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yMetricStatsIn: Sendable, Codable, ParameterConvertible, Hashable {

    /** End is the end of the window as a Unix timestamp in milliseconds. Required. */
    public var end: Int64
    /** Filter narrows the metrics counted. */
    public var filter: O11yO11yMetricFilter?
    /** Limit caps how many metrics come back, between 1 and 5000. Required. */
    public var limit: Int64
    /** Offset is how many metrics to skip, for paging. */
    public var offset: Int64?
    /** OrderBy sorts the page, by samples or timeseries. */
    public var orderBy: O11yO11yMetricOrder?
    /** Start is the start of the window as a Unix timestamp in milliseconds. Required. */
    public var start: Int64

    public init(end: Int64, filter: O11yO11yMetricFilter? = nil, limit: Int64, offset: Int64? = nil, orderBy: O11yO11yMetricOrder? = nil, start: Int64) {
        self.end = end
        self.filter = filter
        self.limit = limit
        self.offset = offset
        self.orderBy = orderBy
        self.start = start
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case end
        case filter
        case limit
        case offset
        case orderBy
        case start
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(end, forKey: .end)
        try container.encodeIfPresent(filter, forKey: .filter)
        try container.encode(limit, forKey: .limit)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(orderBy, forKey: .orderBy)
        try container.encode(start, forKey: .start)
    }
}

