//
// O11yO11yLLMPricingRulesPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yLLMPricingRulesPage: Sendable, Codable, ParameterConvertible, Hashable {

    /** Items are the rules. */
    public var items: [O11yO11yLLMPricingRule]?
    /** Limit is the page cap the read ran with. */
    public var limit: Int?
    /** Offset is the row offset this page started at. */
    public var offset: Int?
    /** Total is how many rules match, across all pages. */
    public var total: Int?

    public init(items: [O11yO11yLLMPricingRule]? = nil, limit: Int? = nil, offset: Int? = nil, total: Int? = nil) {
        self.items = items
        self.limit = limit
        self.offset = offset
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case limit
        case offset
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

