//
// O11yIntegrationConnectionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yIntegrationConnectionStatus: Sendable, Codable, ParameterConvertible, Hashable {

    public var logs: O11ySignalConnectionStatus?
    public var metrics: O11ySignalConnectionStatus?

    public init(logs: O11ySignalConnectionStatus? = nil, metrics: O11ySignalConnectionStatus? = nil) {
        self.logs = logs
        self.metrics = metrics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case logs
        case metrics
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(logs, forKey: .logs)
        try container.encodeIfPresent(metrics, forKey: .metrics)
    }
}

