//
// O11yO11ySignalFilters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11ySignalFilters: Sendable, Codable, ParameterConvertible, Hashable {

    /** Filters are the attributes offered, in display order. */
    public var filters: [O11yO11yFilterKey]?
    /** Signal is the signal the filters belong to. */
    public var signal: String?

    public init(filters: [O11yO11yFilterKey]? = nil, signal: String? = nil) {
        self.filters = filters
        self.signal = signal
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filters
        case signal
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filters, forKey: .filters)
        try container.encodeIfPresent(signal, forKey: .signal)
    }
}

