//
// O11yLLM.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yLLM: Sendable, Codable, ParameterConvertible, Hashable {

    public var costUsd: Double?
    public var generations: Int?

    public init(costUsd: Double? = nil, generations: Int? = nil) {
        self.costUsd = costUsd
        self.generations = generations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case costUsd
        case generations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(costUsd, forKey: .costUsd)
        try container.encodeIfPresent(generations, forKey: .generations)
    }
}

