//
// O11yO11yUsageItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yUsageItem: Sendable, Codable, ParameterConvertible, Hashable {

    /** Count is how many spans were ingested in the bucket. */
    public var count: Int?
    /** Time is the bucket start. */
    public var time: Date?
    /** Timestamp is the bucket start, as epoch nanoseconds. */
    public var timestamp: Int?

    public init(count: Int? = nil, time: Date? = nil, timestamp: Int? = nil) {
        self.count = count
        self.time = time
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case time
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
    }
}

