//
// O11yO11yInfraDaemonSetsOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yInfraDaemonSetsOut: Sendable, Codable, ParameterConvertible, Hashable {

    /** Data holds the rows. */
    public var data: O11yDaemonSets?
    /** Status is \"success\". */
    public var status: String?

    public init(data: O11yDaemonSets? = nil, status: String? = nil) {
        self.data = data
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

