//
// O11yO11yPublicDashboardWriteIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct O11yO11yPublicDashboardWriteIn: Sendable, Codable, ParameterConvertible, Hashable {

    public var defaultTimeRange: String?
    /** ID is the dashboard id from the path. */
    public var id: String?
    public var timeRangeEnabled: Bool?

    public init(defaultTimeRange: String? = nil, id: String? = nil, timeRangeEnabled: Bool? = nil) {
        self.defaultTimeRange = defaultTimeRange
        self.id = id
        self.timeRangeEnabled = timeRangeEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case defaultTimeRange
        case id
        case timeRangeEnabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(defaultTimeRange, forKey: .defaultTimeRange)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timeRangeEnabled, forKey: .timeRangeEnabled)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension O11yO11yPublicDashboardWriteIn: Identifiable {}
