//
// ObjectItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ObjectItem: Sendable, Codable, ParameterConvertible, Hashable {

    public var etag: String?
    /** true for a folder (common prefix) */
    public var isDir: Bool?
    /** key RELATIVE to the requested prefix */
    public var key: String?
    /** unix seconds (0 for a folder) */
    public var lastModified: Int?
    /** bytes (0 for a folder) */
    public var size: Int?

    public init(etag: String? = nil, isDir: Bool? = nil, key: String? = nil, lastModified: Int? = nil, size: Int? = nil) {
        self.etag = etag
        self.isDir = isDir
        self.key = key
        self.lastModified = lastModified
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case etag
        case isDir
        case key
        case lastModified
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(isDir, forKey: .isDir)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(lastModified, forKey: .lastModified)
        try container.encodeIfPresent(size, forKey: .size)
    }
}

