//
// ObserveStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ObserveStatusResponse: Codable, JSONEncodable, Hashable {

    public enum Source: String, Codable, CaseIterable {
        case probe = "probe"
        case scrape = "scrape"
        case _none = "none"
    }
    public var product: String?
    public var up: Bool?
    /** Health-probe round trip; -1 when the probe did not complete. */
    public var latencyMs: Double?
    /** Health-probe status code (0 = no response). */
    public var httpCode: Int?
    /** VictoriaMetrics up{service}: 1/0, or null when no scrape target. */
    public var scrapeUp: Int?
    public var probeUrl: String?
    /** Which signal set `up`. */
    public var source: Source?
    /** RFC3339 timestamp (UTC). */
    public var checkedAt: String?

    public init(product: String? = nil, up: Bool? = nil, latencyMs: Double? = nil, httpCode: Int? = nil, scrapeUp: Int? = nil, probeUrl: String? = nil, source: Source? = nil, checkedAt: String? = nil) {
        self.product = product
        self.up = up
        self.latencyMs = latencyMs
        self.httpCode = httpCode
        self.scrapeUp = scrapeUp
        self.probeUrl = probeUrl
        self.source = source
        self.checkedAt = checkedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case product
        case up
        case latencyMs
        case httpCode
        case scrapeUp
        case probeUrl
        case source
        case checkedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(product, forKey: .product)
        try container.encodeIfPresent(up, forKey: .up)
        try container.encodeIfPresent(latencyMs, forKey: .latencyMs)
        try container.encodeIfPresent(httpCode, forKey: .httpCode)
        try container.encodeIfPresent(scrapeUp, forKey: .scrapeUp)
        try container.encodeIfPresent(probeUrl, forKey: .probeUrl)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(checkedAt, forKey: .checkedAt)
    }
}

