//
// Op.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Op: Sendable, Codable, ParameterConvertible, Hashable {

    public var href: String?
    public var method: String?
    public var operationId: String?
    public var summary: String?

    public init(href: String? = nil, method: String? = nil, operationId: String? = nil, summary: String? = nil) {
        self.href = href
        self.method = method
        self.operationId = operationId
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case href
        case method
        case operationId
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(href, forKey: .href)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(operationId, forKey: .operationId)
        try container.encodeIfPresent(summary, forKey: .summary)
    }
}

