//
// Page.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Page: Sendable, Codable, ParameterConvertible, Hashable {

    public var body: String?
    public var enabled: Bool?
    public var id: String?
    public var title: String?

    public init(body: String? = nil, enabled: Bool? = nil, id: String? = nil, title: String? = nil) {
        self.body = body
        self.enabled = enabled
        self.id = id
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case enabled
        case id
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Page: Identifiable {}
