//
// PlatformServerCreateRequestJson.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlatformServerCreateRequestJson: Codable, JSONEncodable, Hashable {

    public var name: String
    public var description: String?
    public var ipAddress: String
    public var port: Int?
    public var username: String?
    public var sshKeyId: String

    public init(name: String, description: String? = nil, ipAddress: String, port: Int? = nil, username: String? = nil, sshKeyId: String) {
        self.name = name
        self.description = description
        self.ipAddress = ipAddress
        self.port = port
        self.username = username
        self.sshKeyId = sshKeyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case ipAddress
        case port
        case username
        case sshKeyId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(ipAddress, forKey: .ipAddress)
        try container.encodeIfPresent(port, forKey: .port)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encode(sshKeyId, forKey: .sshKeyId)
    }
}

