//
// PlatformApplicationSaveGitProdiverRequestJson.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlatformApplicationSaveGitProdiverRequestJson: Codable, JSONEncodable, Hashable {

    public var applicationId: String
    public var customGitBranch: String?
    public var customGitBuildPath: String?
    public var customGitUrl: String?
    public var customGitSSHKeyId: String?

    public init(applicationId: String, customGitBranch: String? = nil, customGitBuildPath: String? = nil, customGitUrl: String? = nil, customGitSSHKeyId: String? = nil) {
        self.applicationId = applicationId
        self.customGitBranch = customGitBranch
        self.customGitBuildPath = customGitBuildPath
        self.customGitUrl = customGitUrl
        self.customGitSSHKeyId = customGitSSHKeyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applicationId
        case customGitBranch
        case customGitBuildPath
        case customGitUrl
        case customGitSSHKeyId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(applicationId, forKey: .applicationId)
        try container.encodeIfPresent(customGitBranch, forKey: .customGitBranch)
        try container.encodeIfPresent(customGitBuildPath, forKey: .customGitBuildPath)
        try container.encodeIfPresent(customGitUrl, forKey: .customGitUrl)
        try container.encodeIfPresent(customGitSSHKeyId, forKey: .customGitSSHKeyId)
    }
}

