//
// Posting.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Posting: Sendable, Codable, ParameterConvertible, Hashable {

    public var account: String?
    public var amount: JSONValue?

    public init(account: String? = nil, amount: JSONValue? = nil) {
        self.account = account
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(amount, forKey: .amount)
    }
}

