//
// PresetAccepted.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PresetAccepted: Sendable, Codable, ParameterConvertible, Hashable {

    /** Note explains what acceptance does and does not promise. */
    public var note: String?
    /** Preset is the blend with its defaults filled in. */
    public var preset: Preset?
    /** ServedAs is the model id the serving layer would resolve this blend under. */
    public var servedAs: String?
    /** Status is \"accepted\": the blend is well-formed, not that it is now served. */
    public var status: String?

    public init(note: String? = nil, preset: Preset? = nil, servedAs: String? = nil, status: String? = nil) {
        self.note = note
        self.preset = preset
        self.servedAs = servedAs
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case note
        case preset
        case servedAs = "served_as"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(preset, forKey: .preset)
        try container.encodeIfPresent(servedAs, forKey: .servedAs)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

