//
// PricingPricingModelsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PricingPricingModelsResponse: Codable, JSONEncodable, Hashable {

    public var updated: Date?
    public var total: Int?
    public var models: [PricingModel]?

    public init(updated: Date? = nil, total: Int? = nil, models: [PricingModel]? = nil) {
        self.updated = updated
        self.total = total
        self.models = models
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updated
        case total
        case models
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(models, forKey: .models)
    }
}

