//
// ProgramApplication.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProgramApplication: Sendable, Codable, ParameterConvertible, Hashable {

    /** Company is the applicant's company name. */
    public var company: String?
    /** CompanyID is the CRM Company minted for this lead at intake, so the startup also appears in the org's standard CRM tabs. Empty when that best-effort projection did not run. */
    public var companyId: String?
    /** ContactID is the CRM Contact minted for this lead at intake. Empty when that best-effort projection did not run. */
    public var contactId: String?
    /** ContactName is the person who applied. */
    public var contactName: String?
    /** CreatedAt is the unix second the application arrived. Server-owned. */
    public var createdAt: Int?
    /** Email is the applicant's email — half of the (email, company) key a resubmission refreshes instead of duplicating. */
    public var email: String?
    /** Events is the append-only stage-transition log, oldest first. */
    public var events: [StageEvent]?
    /** ID is the server-minted application id (\"appl_\" + 128 random bits). */
    public var id: String?
    /** Metadata is the FULL submitted form, every field, including the arrays the promoted columns above do not carry (tier1Investors, useCases) and the deterministic tier1Matched list. */
    public var metadata: [String: JSONValue]?
    /** Reason is why the application was rejected, required to reject. Empty otherwise. */
    public var reason: String?
    /** Role is the applicant's role at their company. */
    public var role: String?
    /** Screen is the AI screen. It runs after intake, so a freshly created application carries a \"pending\" screen. */
    public var screen: ScreenResult?
    /** Stage is the pipeline stage: applied, screened, qualified, credits-offered, onboarded or rejected. Server-owned — it starts at \"applied\" and moves only through the transition machine. */
    public var stage: String?
    /** Tier1 is whether the applicant is tier-1 backed, derived deterministically at intake from the submitted fund list — independent of the AI screen. */
    public var tier1: Bool?
    /** UpdatedAt is the unix second of the last write. Server-owned. */
    public var updatedAt: Int?
    /** Website is the applicant's website as submitted. */
    public var website: String?

    public init(company: String? = nil, companyId: String? = nil, contactId: String? = nil, contactName: String? = nil, createdAt: Int? = nil, email: String? = nil, events: [StageEvent]? = nil, id: String? = nil, metadata: [String: JSONValue]? = nil, reason: String? = nil, role: String? = nil, screen: ScreenResult? = nil, stage: String? = nil, tier1: Bool? = nil, updatedAt: Int? = nil, website: String? = nil) {
        self.company = company
        self.companyId = companyId
        self.contactId = contactId
        self.contactName = contactName
        self.createdAt = createdAt
        self.email = email
        self.events = events
        self.id = id
        self.metadata = metadata
        self.reason = reason
        self.role = role
        self.screen = screen
        self.stage = stage
        self.tier1 = tier1
        self.updatedAt = updatedAt
        self.website = website
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case company
        case companyId
        case contactId
        case contactName
        case createdAt
        case email
        case events
        case id
        case metadata
        case reason
        case role
        case screen
        case stage
        case tier1
        case updatedAt
        case website
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(companyId, forKey: .companyId)
        try container.encodeIfPresent(contactId, forKey: .contactId)
        try container.encodeIfPresent(contactName, forKey: .contactName)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(screen, forKey: .screen)
        try container.encodeIfPresent(stage, forKey: .stage)
        try container.encodeIfPresent(tier1, forKey: .tier1)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(website, forKey: .website)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProgramApplication: Identifiable {}
