//
// ProjectsCreateProjectRequestRepo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProjectsCreateProjectRequestRepo: Codable, JSONEncodable, Hashable {

    public var url: String?
    public var branch: String?

    public init(url: String? = nil, branch: String? = nil) {
        self.url = url
        self.branch = branch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case branch
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(branch, forKey: .branch)
    }
}

