//
// PromptsPromptMetric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PromptsPromptMetric: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var type: String?
    /** True version count */
    public var versions: Int?
    public var currentVersion: Int?
    public var createdAt: Date?
    public var lastUpdatedAt: Date?

    public init(name: String? = nil, type: String? = nil, versions: Int? = nil, currentVersion: Int? = nil, createdAt: Date? = nil, lastUpdatedAt: Date? = nil) {
        self.name = name
        self.type = type
        self.versions = versions
        self.currentVersion = currentVersion
        self.createdAt = createdAt
        self.lastUpdatedAt = lastUpdatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case versions
        case currentVersion
        case createdAt
        case lastUpdatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(versions, forKey: .versions)
        try container.encodeIfPresent(currentVersion, forKey: .currentVersion)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(lastUpdatedAt, forKey: .lastUpdatedAt)
    }
}

