//
// ProvisionResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProvisionResult: Sendable, Codable, ParameterConvertible, Hashable {

    /** ConnectionString is the ready-to-use DSN, credential included. RETURNED HERE ONCE: no read beside this one carries it, so a caller that does not keep it must provision again. */
    public var connectionString: String?
    /** Database is the logical database, collection, index or bucket this resource resolves to on its backend. It is derived from Name under an org-namespacing hash, so it is not Name and two orgs cannot land on one. */
    public var database: String?
    /** Host is the address that routes to this resource — a dedicated instance's own in-cluster Service, or the public gateway for a shared one. Never the internal admin address of a shared backend. */
    public var host: String?
    /** ID is the resource's server-minted handle, \"rs_\"-prefixed. The caller does not choose it, and it is what every read and the delete address. */
    public var id: String?
    /** Kind is the product provisioned: sql, vector, datastore, kv, search, s3 or docdb. It is the route that was called, not a body field. */
    public var kind: String?
    /** Name is the org-unique slug the caller asked for, lower-cased. Every physical name on the backend derives from it. */
    public var name: String?
    /** Password is the minted credential, in plaintext, for the kinds that have one. RETURNED HERE ONCE — where KMS is configured it is sealed there and only a reference is persisted; where it is not, it is stored nowhere at all. It is never held in plaintext on either side. */
    public var password: String?
    /** Port is the port a client connects to on Host. */
    public var port: Int64?
    /** Status is \"ready\", or \"provisioning\" while a dedicated instance is still being materialized by the operator. A shared-backend create is \"ready\" here; a dedicated one answers 201 still launching, and reaches ready only when a later read reconciles it against the operator's live CR — never fabricated. */
    public var status: String?
    /** Username is the credential's user, for the kinds that mint one per resource. Absent for a kind whose backend authenticates with a shared, out-of-band key. */
    public var username: String?

    public init(connectionString: String? = nil, database: String? = nil, host: String? = nil, id: String? = nil, kind: String? = nil, name: String? = nil, password: String? = nil, port: Int64? = nil, status: String? = nil, username: String? = nil) {
        self.connectionString = connectionString
        self.database = database
        self.host = host
        self.id = id
        self.kind = kind
        self.name = name
        self.password = password
        self.port = port
        self.status = status
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case connectionString
        case database
        case host
        case id
        case kind
        case name
        case password
        case port
        case status
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(connectionString, forKey: .connectionString)
        try container.encodeIfPresent(database, forKey: .database)
        try container.encodeIfPresent(host, forKey: .host)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(port, forKey: .port)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(username, forKey: .username)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProvisionResult: Identifiable {}
