//
// Provider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Provider: Sendable, Codable, ParameterConvertible, Hashable {

    public var apiVersion: String?
    public var asset: String?
    public var browserUrl: String?
    public var category: String?
    public var chain: String?
    public var clientId: String?
    public var clientSecret: String?
    public var compatibleProvider: String?
    public var configText: String?
    public var contractMethod: String?
    public var contractName: String?
    public var createdTime: String?
    public var currency: String?
    public var displayName: String?
    public var enableThinking: Bool?
    public var errorText: String?
    public var flavor: String?
    public var frequencyPenalty: Double?
    public var inputPricePerThousandTokens: Double?
    public var isDefault: Bool?
    public var isRemote: Bool?
    public var mcpTools: [AgentMcpTools]?
    public var name: String?
    public var network: String?
    public var outputPricePerThousandTokens: Double?
    public var owner: String?
    public var presencePenalty: Double?
    public var providerKey: String?
    public var providerUrl: String?
    public var rawText: String?
    public var region: String?
    public var resultSummary: String?
    public var runner: String?
    public var signCert: String?
    public var signKey: String?
    public var state: String?
    public var subType: String?
    public var target: String?
    public var targetMode: String?
    public var temperature: Double?
    public var testContent: String?
    public var text: String?
    public var topK: Int?
    public var topP: Double?
    public var type: String?
    public var userCert: String?
    public var userKey: String?

    public init(apiVersion: String? = nil, asset: String? = nil, browserUrl: String? = nil, category: String? = nil, chain: String? = nil, clientId: String? = nil, clientSecret: String? = nil, compatibleProvider: String? = nil, configText: String? = nil, contractMethod: String? = nil, contractName: String? = nil, createdTime: String? = nil, currency: String? = nil, displayName: String? = nil, enableThinking: Bool? = nil, errorText: String? = nil, flavor: String? = nil, frequencyPenalty: Double? = nil, inputPricePerThousandTokens: Double? = nil, isDefault: Bool? = nil, isRemote: Bool? = nil, mcpTools: [AgentMcpTools]? = nil, name: String? = nil, network: String? = nil, outputPricePerThousandTokens: Double? = nil, owner: String? = nil, presencePenalty: Double? = nil, providerKey: String? = nil, providerUrl: String? = nil, rawText: String? = nil, region: String? = nil, resultSummary: String? = nil, runner: String? = nil, signCert: String? = nil, signKey: String? = nil, state: String? = nil, subType: String? = nil, target: String? = nil, targetMode: String? = nil, temperature: Double? = nil, testContent: String? = nil, text: String? = nil, topK: Int? = nil, topP: Double? = nil, type: String? = nil, userCert: String? = nil, userKey: String? = nil) {
        self.apiVersion = apiVersion
        self.asset = asset
        self.browserUrl = browserUrl
        self.category = category
        self.chain = chain
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.compatibleProvider = compatibleProvider
        self.configText = configText
        self.contractMethod = contractMethod
        self.contractName = contractName
        self.createdTime = createdTime
        self.currency = currency
        self.displayName = displayName
        self.enableThinking = enableThinking
        self.errorText = errorText
        self.flavor = flavor
        self.frequencyPenalty = frequencyPenalty
        self.inputPricePerThousandTokens = inputPricePerThousandTokens
        self.isDefault = isDefault
        self.isRemote = isRemote
        self.mcpTools = mcpTools
        self.name = name
        self.network = network
        self.outputPricePerThousandTokens = outputPricePerThousandTokens
        self.owner = owner
        self.presencePenalty = presencePenalty
        self.providerKey = providerKey
        self.providerUrl = providerUrl
        self.rawText = rawText
        self.region = region
        self.resultSummary = resultSummary
        self.runner = runner
        self.signCert = signCert
        self.signKey = signKey
        self.state = state
        self.subType = subType
        self.target = target
        self.targetMode = targetMode
        self.temperature = temperature
        self.testContent = testContent
        self.text = text
        self.topK = topK
        self.topP = topP
        self.type = type
        self.userCert = userCert
        self.userKey = userKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apiVersion
        case asset
        case browserUrl
        case category
        case chain
        case clientId
        case clientSecret
        case compatibleProvider
        case configText
        case contractMethod
        case contractName
        case createdTime
        case currency
        case displayName
        case enableThinking
        case errorText
        case flavor
        case frequencyPenalty
        case inputPricePerThousandTokens
        case isDefault
        case isRemote
        case mcpTools
        case name
        case network
        case outputPricePerThousandTokens
        case owner
        case presencePenalty
        case providerKey
        case providerUrl
        case rawText
        case region
        case resultSummary
        case runner
        case signCert
        case signKey
        case state
        case subType
        case target
        case targetMode
        case temperature
        case testContent
        case text
        case topK
        case topP
        case type
        case userCert
        case userKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(apiVersion, forKey: .apiVersion)
        try container.encodeIfPresent(asset, forKey: .asset)
        try container.encodeIfPresent(browserUrl, forKey: .browserUrl)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(chain, forKey: .chain)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(clientSecret, forKey: .clientSecret)
        try container.encodeIfPresent(compatibleProvider, forKey: .compatibleProvider)
        try container.encodeIfPresent(configText, forKey: .configText)
        try container.encodeIfPresent(contractMethod, forKey: .contractMethod)
        try container.encodeIfPresent(contractName, forKey: .contractName)
        try container.encodeIfPresent(createdTime, forKey: .createdTime)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(enableThinking, forKey: .enableThinking)
        try container.encodeIfPresent(errorText, forKey: .errorText)
        try container.encodeIfPresent(flavor, forKey: .flavor)
        try container.encodeIfPresent(frequencyPenalty, forKey: .frequencyPenalty)
        try container.encodeIfPresent(inputPricePerThousandTokens, forKey: .inputPricePerThousandTokens)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(isRemote, forKey: .isRemote)
        try container.encodeIfPresent(mcpTools, forKey: .mcpTools)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(network, forKey: .network)
        try container.encodeIfPresent(outputPricePerThousandTokens, forKey: .outputPricePerThousandTokens)
        try container.encodeIfPresent(owner, forKey: .owner)
        try container.encodeIfPresent(presencePenalty, forKey: .presencePenalty)
        try container.encodeIfPresent(providerKey, forKey: .providerKey)
        try container.encodeIfPresent(providerUrl, forKey: .providerUrl)
        try container.encodeIfPresent(rawText, forKey: .rawText)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(resultSummary, forKey: .resultSummary)
        try container.encodeIfPresent(runner, forKey: .runner)
        try container.encodeIfPresent(signCert, forKey: .signCert)
        try container.encodeIfPresent(signKey, forKey: .signKey)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(subType, forKey: .subType)
        try container.encodeIfPresent(target, forKey: .target)
        try container.encodeIfPresent(targetMode, forKey: .targetMode)
        try container.encodeIfPresent(temperature, forKey: .temperature)
        try container.encodeIfPresent(testContent, forKey: .testContent)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(topK, forKey: .topK)
        try container.encodeIfPresent(topP, forKey: .topP)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(userCert, forKey: .userCert)
        try container.encodeIfPresent(userKey, forKey: .userKey)
    }
}

