//
// Question.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Question: Sendable, Codable, ParameterConvertible, Hashable {

    public var account: String?
    /** formatted figure ($…) */
    public var amount: String?
    /** the source transaction id it concerns */
    public var id: String?
    /** outlier|reversal|roundoff|uncosted|overdrawn */
    public var kind: String?
    public var postedAt: String?
    /** the specific question to ask the founder */
    public var text: String?

    public init(account: String? = nil, amount: String? = nil, id: String? = nil, kind: String? = nil, postedAt: String? = nil, text: String? = nil) {
        self.account = account
        self.amount = amount
        self.id = id
        self.kind = kind
        self.postedAt = postedAt
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case amount
        case id
        case kind
        case postedAt
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(postedAt, forKey: .postedAt)
        try container.encodeIfPresent(text, forKey: .text)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Question: Identifiable {}
