//
// ReferralsAdminListData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReferralsAdminListData: Codable, JSONEncodable, Hashable {

    public var referrals: [ReferralsAdminReferralView]?
    public var summary: ReferralsAdminSummary?

    public init(referrals: [ReferralsAdminReferralView]? = nil, summary: ReferralsAdminSummary? = nil) {
        self.referrals = referrals
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case referrals
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(referrals, forKey: .referrals)
        try container.encodeIfPresent(summary, forKey: .summary)
    }
}

