//
// RefreshReferenceIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefreshReferenceIn: Sendable, Codable, ParameterConvertible, Hashable {

    /** Force accepts a take whose size moved past the change bound. A publisher serving a tenth or ten times its previous list is refused by default and the previous version is left standing; this is the operator saying the change is real. It cannot make an empty, truncated or unparseable take land — those are errors, not magnitudes. */
    public var force: Bool?
    /** Receipts are supplied by the component that holds the membership, for a set of kind attest. They are refused on any other kind, and a set of kind attest is refused without them: this plane never invents a freshness it did not observe. */
    public var receipts: [ReferenceReceipt]?
    /** Set is the set to refresh. */
    public var _set: String?

    public init(force: Bool? = nil, receipts: [ReferenceReceipt]? = nil, _set: String? = nil) {
        self.force = force
        self.receipts = receipts
        self._set = _set
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case force
        case receipts
        case _set = "set"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(force, forKey: .force)
        try container.encodeIfPresent(receipts, forKey: .receipts)
        try container.encodeIfPresent(_set, forKey: ._set)
    }
}

