//
// ResearchArtifact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResearchArtifact: Sendable, Codable, ParameterConvertible, Hashable {

    /** base64 bytes on write; the server hashes + stores them (never returned) */
    public var content: String?
    public var gitBranch: String?
    public var gitDirty: Bool?
    public var gitSha: String?
    public var kind: String?
    public var libVersions: JSONValue?
    public var project: String?
    /** server-derived content address (sha256:<hash>) */
    public var ref: String?
    public var retentionClass: String?
    public var runId: String?
    /** SERVER-derived on write; the identity */
    public var sha256: String?
    public var ts: Int?
    public var visibility: String?

    public init(content: String? = nil, gitBranch: String? = nil, gitDirty: Bool? = nil, gitSha: String? = nil, kind: String? = nil, libVersions: JSONValue? = nil, project: String? = nil, ref: String? = nil, retentionClass: String? = nil, runId: String? = nil, sha256: String? = nil, ts: Int? = nil, visibility: String? = nil) {
        self.content = content
        self.gitBranch = gitBranch
        self.gitDirty = gitDirty
        self.gitSha = gitSha
        self.kind = kind
        self.libVersions = libVersions
        self.project = project
        self.ref = ref
        self.retentionClass = retentionClass
        self.runId = runId
        self.sha256 = sha256
        self.ts = ts
        self.visibility = visibility
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case gitBranch = "git_branch"
        case gitDirty = "git_dirty"
        case gitSha = "git_sha"
        case kind
        case libVersions = "lib_versions"
        case project
        case ref
        case retentionClass = "retention_class"
        case runId = "run_id"
        case sha256
        case ts
        case visibility
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(gitBranch, forKey: .gitBranch)
        try container.encodeIfPresent(gitDirty, forKey: .gitDirty)
        try container.encodeIfPresent(gitSha, forKey: .gitSha)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(libVersions, forKey: .libVersions)
        try container.encodeIfPresent(project, forKey: .project)
        try container.encodeIfPresent(ref, forKey: .ref)
        try container.encodeIfPresent(retentionClass, forKey: .retentionClass)
        try container.encodeIfPresent(runId, forKey: .runId)
        try container.encodeIfPresent(sha256, forKey: .sha256)
        try container.encodeIfPresent(ts, forKey: .ts)
        try container.encodeIfPresent(visibility, forKey: .visibility)
    }
}

