//
// Restarted.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Restarted: Sendable, Codable, ParameterConvertible, Hashable {

    /** App is the service that was restarted. */
    public var app: String?
    /** Env is that namespace's lifecycle env. */
    public var env: String?
    /** Namespace is the namespace its Deployment was patched in. */
    public var namespace: String?
    /** OK is always true — a failure is an error, not a false here. */
    public var ok: Bool?
    /** RestartedAt is the timestamp stamped onto the pod template, RFC3339 UTC. */
    public var restartedAt: String?

    public init(app: String? = nil, env: String? = nil, namespace: String? = nil, ok: Bool? = nil, restartedAt: String? = nil) {
        self.app = app
        self.env = env
        self.namespace = namespace
        self.ok = ok
        self.restartedAt = restartedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case env
        case namespace
        case ok
        case restartedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(env, forKey: .env)
        try container.encodeIfPresent(namespace, forKey: .namespace)
        try container.encodeIfPresent(ok, forKey: .ok)
        try container.encodeIfPresent(restartedAt, forKey: .restartedAt)
    }
}

