//
// RiskDatasetRows.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RiskDatasetRows: Sendable, Codable, ParameterConvertible, Hashable {

    /** Dataset is the dataset the page was read from. */
    public var dataset: String?
    /** Digest is the version's fingerprint. An exported page that did not carry it would be bytes with no way to say which dataset they are. */
    public var digest: String?
    /** Dims names what each coordinate of Point means, in Point's own order. */
    public var dims: [String]?
    /** Limit is the page size actually served: the one asked for, clamped to the plane's own bound of 5000. Fewer rows than Limit means the version ended. */
    public var limit: Int?
    /** Offset is where this page starts in the version's own row order, which is by row id and therefore stable forever. */
    public var offset: Int?
    /** Rows is the page. Never null. */
    public var rows: [RiskDatasetRow]?
    /** Version is which published version it was read from — the one asked for, or the newest published one when the request named none. */
    public var version: Int?

    public init(dataset: String? = nil, digest: String? = nil, dims: [String]? = nil, limit: Int? = nil, offset: Int? = nil, rows: [RiskDatasetRow]? = nil, version: Int? = nil) {
        self.dataset = dataset
        self.digest = digest
        self.dims = dims
        self.limit = limit
        self.offset = offset
        self.rows = rows
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataset
        case digest
        case dims
        case limit
        case offset
        case rows
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dataset, forKey: .dataset)
        try container.encodeIfPresent(digest, forKey: .digest)
        try container.encodeIfPresent(dims, forKey: .dims)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(rows, forKey: .rows)
        try container.encodeIfPresent(version, forKey: .version)
    }
}

