//
// RoleList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RoleList: Sendable, Codable, ParameterConvertible, Hashable {

    /** Data is every (user, role) assignment in the caller's org. */
    public var data: [RoleAssignment]?

    public init(data: [RoleAssignment]? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

