//
// SaaSRevenue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SaaSRevenue: Sendable, Codable, ParameterConvertible, Hashable {

    public var activeSubscriptions: Int?
    public var arrCents: Int?
    public var byCategory: [SaaSCategory]?
    public var churnedMrrCents: Int?
    public var mrrCents: Int?
    public var netNewMrrCents: Int?
    public var newMrrCents: Int?
    public var payingCustomers: Int?
    public var trials: Int?

    public init(activeSubscriptions: Int? = nil, arrCents: Int? = nil, byCategory: [SaaSCategory]? = nil, churnedMrrCents: Int? = nil, mrrCents: Int? = nil, netNewMrrCents: Int? = nil, newMrrCents: Int? = nil, payingCustomers: Int? = nil, trials: Int? = nil) {
        self.activeSubscriptions = activeSubscriptions
        self.arrCents = arrCents
        self.byCategory = byCategory
        self.churnedMrrCents = churnedMrrCents
        self.mrrCents = mrrCents
        self.netNewMrrCents = netNewMrrCents
        self.newMrrCents = newMrrCents
        self.payingCustomers = payingCustomers
        self.trials = trials
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activeSubscriptions
        case arrCents
        case byCategory
        case churnedMrrCents
        case mrrCents
        case netNewMrrCents
        case newMrrCents
        case payingCustomers
        case trials
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(activeSubscriptions, forKey: .activeSubscriptions)
        try container.encodeIfPresent(arrCents, forKey: .arrCents)
        try container.encodeIfPresent(byCategory, forKey: .byCategory)
        try container.encodeIfPresent(churnedMrrCents, forKey: .churnedMrrCents)
        try container.encodeIfPresent(mrrCents, forKey: .mrrCents)
        try container.encodeIfPresent(netNewMrrCents, forKey: .netNewMrrCents)
        try container.encodeIfPresent(newMrrCents, forKey: .newMrrCents)
        try container.encodeIfPresent(payingCustomers, forKey: .payingCustomers)
        try container.encodeIfPresent(trials, forKey: .trials)
    }
}

