//
// Scale.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Scale: Sendable, Codable, ParameterConvertible, Hashable {

    public var createdTime: String?
    public var displayName: String?
    public var name: String?
    public var owner: String?
    public var state: String?
    public var text: String?

    public init(createdTime: String? = nil, displayName: String? = nil, name: String? = nil, owner: String? = nil, state: String? = nil, text: String? = nil) {
        self.createdTime = createdTime
        self.displayName = displayName
        self.name = name
        self.owner = owner
        self.state = state
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdTime
        case displayName
        case name
        case owner
        case state
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdTime, forKey: .createdTime)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(owner, forKey: .owner)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(text, forKey: .text)
    }
}

