//
// SearchIndex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchIndex: Sendable, Codable, ParameterConvertible, Hashable {

    /** CreatedAt is the index's creation time (RFC 3339); it falls back to now when the index list could not be read. */
    public var createdAt: String?
    /** DocCount is how many documents the index currently holds. */
    public var docCount: Int?
    /** LastIndexedAt is the index's last update time (RFC 3339), null when the index list could not be read. */
    public var lastIndexedAt: String?
    /** Name is the index uid. */
    public var name: String?

    public init(createdAt: String? = nil, docCount: Int? = nil, lastIndexedAt: String? = nil, name: String? = nil) {
        self.createdAt = createdAt
        self.docCount = docCount
        self.lastIndexedAt = lastIndexedAt
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case docCount
        case lastIndexedAt
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(docCount, forKey: .docCount)
        try container.encodeIfPresent(lastIndexedAt, forKey: .lastIndexedAt)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

