//
// SeoCompetitorOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SeoCompetitorOut: Sendable, Codable, ParameterConvertible, Hashable {

    /** Competitors is one row per domain, strongest first. */
    public var competitors: [SeoDomain]?
    /** Cost is what this call cost, in USD, as an exact decimal string. */
    public var cost: String?
    /** Total is how many domains the upstream holds for these phrases. */
    public var total: Int?

    public init(competitors: [SeoDomain]? = nil, cost: String? = nil, total: Int? = nil) {
        self.competitors = competitors
        self.cost = cost
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case competitors
        case cost
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(competitors, forKey: .competitors)
        try container.encodeIfPresent(cost, forKey: .cost)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

