//
// SessionEnded.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SessionEnded: Sendable, Codable, ParameterConvertible, Hashable {

    /** LoggedIn is always false — this is the answer to having just signed out, so it states the resulting session state rather than reporting the request's outcome. It is not omitempty: false is the whole answer. */
    public var loggedIn: Bool?
    /** LoginURL is where to sign in again. Always present, because a caller that has just signed out is exactly the caller who needs it. */
    public var loginUrl: String?

    public init(loggedIn: Bool? = nil, loginUrl: String? = nil) {
        self.loggedIn = loggedIn
        self.loginUrl = loginUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case loggedIn
        case loginUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(loggedIn, forKey: .loggedIn)
        try container.encodeIfPresent(loginUrl, forKey: .loginUrl)
    }
}

