//
// SpaceList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpaceList: Sendable, Codable, ParameterConvertible, Hashable {

    /** Spaces are the caller org's spaces, oldest first as the store returns them. */
    public var spaces: [SpaceItem]?
    /** Total is how many spaces this org has. It equals len(spaces): the listing is not paged, because one bucket per (org, space) keeps an org's count small by construction, which is the whole reason a drive is a prefix and not a bucket. */
    public var total: Int?

    public init(spaces: [SpaceItem]? = nil, total: Int? = nil) {
        self.spaces = spaces
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case spaces
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(spaces, forKey: .spaces)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

