//
// StatusView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StatusView: Sendable, Codable, ParameterConvertible, Hashable {

    /** Disclaimer states that statuses are provider-reported, never a platform assertion of legal or regulatory compliance. */
    public var disclaimer: String?
    /** Provider is the wired verification provider's name. */
    public var provider: String?
    /** Verifications tallies the org's verifications by provider-reported status. */
    public var verifications: VerificationTally?

    public init(disclaimer: String? = nil, provider: String? = nil, verifications: VerificationTally? = nil) {
        self.disclaimer = disclaimer
        self.provider = provider
        self.verifications = verifications
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case disclaimer
        case provider
        case verifications
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(disclaimer, forKey: .disclaimer)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(verifications, forKey: .verifications)
    }
}

