//
// StreamTopicConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StreamTopicConfig: Codable, JSONEncodable, Hashable {

    public enum CleanupPolicy: String, Codable, CaseIterable {
        case delete = "delete"
        case compact = "compact"
    }
    public enum CompressionType: String, Codable, CaseIterable {
        case _none = "none"
        case gzip = "gzip"
        case snappy = "snappy"
        case lz4 = "lz4"
        case zstd = "zstd"
    }
    /** Message retention in milliseconds */
    public var retentionMs: Int? = -1
    public var cleanupPolicy: CleanupPolicy? = .delete
    public var compressionType: CompressionType? = ._none

    public init(retentionMs: Int? = -1, cleanupPolicy: CleanupPolicy? = .delete, compressionType: CompressionType? = ._none) {
        self.retentionMs = retentionMs
        self.cleanupPolicy = cleanupPolicy
        self.compressionType = compressionType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case retentionMs = "retention_ms"
        case cleanupPolicy = "cleanup_policy"
        case compressionType = "compression_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(retentionMs, forKey: .retentionMs)
        try container.encodeIfPresent(cleanupPolicy, forKey: .cleanupPolicy)
        try container.encodeIfPresent(compressionType, forKey: .compressionType)
    }
}

