//
// StreamBrokerInfoConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StreamBrokerInfoConfig: Codable, JSONEncodable, Hashable {

    public enum Storage: String, Codable, CaseIterable {
        case file = "file"
        case memory = "memory"
    }
    public var replicas: Int?
    public var storage: Storage?

    public init(replicas: Int? = nil, storage: Storage? = nil) {
        self.replicas = replicas
        self.storage = storage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case replicas
        case storage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(replicas, forKey: .replicas)
        try container.encodeIfPresent(storage, forKey: .storage)
    }
}

