//
// TagConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TagConfig: Sendable, Codable, ParameterConvertible, Hashable {

    public var tags: [BrowserTagOut]?

    public init(tags: [BrowserTagOut]? = nil) {
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

