//
// TeamMessages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TeamMessages: Sendable, Codable, ParameterConvertible, Hashable {

    /** Messages are the room's, oldest first, at most `messageMax` of them. */
    public var messages: [TeamMessage]?

    public init(messages: [TeamMessage]? = nil) {
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(messages, forKey: .messages)
    }
}

