//
// Template.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Template: Sendable, Codable, ParameterConvertible, Hashable {

    public var basicConfigOptions: [TemplateConfigOption]?
    public var createdTime: String?
    public var description: String?
    public var displayName: String?
    public var enableBasicConfig: Bool?
    public var icon: String?
    public var manifest: String?
    public var name: String?
    public var owner: String?
    public var readme: String?
    public var updatedTime: String?
    public var version: String?

    public init(basicConfigOptions: [TemplateConfigOption]? = nil, createdTime: String? = nil, description: String? = nil, displayName: String? = nil, enableBasicConfig: Bool? = nil, icon: String? = nil, manifest: String? = nil, name: String? = nil, owner: String? = nil, readme: String? = nil, updatedTime: String? = nil, version: String? = nil) {
        self.basicConfigOptions = basicConfigOptions
        self.createdTime = createdTime
        self.description = description
        self.displayName = displayName
        self.enableBasicConfig = enableBasicConfig
        self.icon = icon
        self.manifest = manifest
        self.name = name
        self.owner = owner
        self.readme = readme
        self.updatedTime = updatedTime
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case basicConfigOptions
        case createdTime
        case description
        case displayName
        case enableBasicConfig
        case icon
        case manifest
        case name
        case owner
        case readme
        case updatedTime
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(basicConfigOptions, forKey: .basicConfigOptions)
        try container.encodeIfPresent(createdTime, forKey: .createdTime)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(enableBasicConfig, forKey: .enableBasicConfig)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(manifest, forKey: .manifest)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(owner, forKey: .owner)
        try container.encodeIfPresent(readme, forKey: .readme)
        try container.encodeIfPresent(updatedTime, forKey: .updatedTime)
        try container.encodeIfPresent(version, forKey: .version)
    }
}

