//
// TrafficPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrafficPoint: Sendable, Codable, ParameterConvertible, Hashable {

    public var byService: [String: Int]?
    public var byTask: [String: Int]?
    public var count: Int?
    public var country: String?
    public var lat: Double?
    public var lon: Double?
    public var region: String?

    public init(byService: [String: Int]? = nil, byTask: [String: Int]? = nil, count: Int? = nil, country: String? = nil, lat: Double? = nil, lon: Double? = nil, region: String? = nil) {
        self.byService = byService
        self.byTask = byTask
        self.count = count
        self.country = country
        self.lat = lat
        self.lon = lon
        self.region = region
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case byService
        case byTask
        case count
        case country
        case lat
        case lon
        case region
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(byService, forKey: .byService)
        try container.encodeIfPresent(byTask, forKey: .byTask)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(lat, forKey: .lat)
        try container.encodeIfPresent(lon, forKey: .lon)
        try container.encodeIfPresent(region, forKey: .region)
    }
}

