//
// TriggerView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TriggerView: Sendable, Codable, ParameterConvertible, Hashable {

    /** whether it currently fires */
    public var enabled: Bool?
    /** the function it calls */
    public var functionName: String?
    /** the trigger's handle */
    public var id: String?
    /** a human label for it */
    public var name: String?
    /** the path it calls */
    public var target: String?
    /** what kind of trigger it is; HTTP is the only one today */
    public var type: String?

    public init(enabled: Bool? = nil, functionName: String? = nil, id: String? = nil, name: String? = nil, target: String? = nil, type: String? = nil) {
        self.enabled = enabled
        self.functionName = functionName
        self.id = id
        self.name = name
        self.target = target
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case functionName
        case id
        case name
        case target
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(functionName, forKey: .functionName)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(target, forKey: .target)
        try container.encodeIfPresent(type, forKey: .type)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TriggerView: Identifiable {}
