//
// UsageTotals.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UsageTotals: Sendable, Codable, ParameterConvertible, Hashable {

    public var requests: Int?
    public var spendCents: Int?
    public var tokens: Int?

    public init(requests: Int? = nil, spendCents: Int? = nil, tokens: Int? = nil) {
        self.requests = requests
        self.spendCents = spendCents
        self.tokens = tokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requests
        case spendCents
        case tokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(requests, forKey: .requests)
        try container.encodeIfPresent(spendCents, forKey: .spendCents)
        try container.encodeIfPresent(tokens, forKey: .tokens)
    }
}

