//
// VectorScoredPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VectorScoredPoint: Codable, JSONEncodable, Hashable {

    public var id: VectorDeletePointsRequestPointsInner?
    public var version: Int?
    public var score: Double?
    public var payload: AnyCodable?
    public var vector: VectorScoredPointVector?

    public init(id: VectorDeletePointsRequestPointsInner? = nil, version: Int? = nil, score: Double? = nil, payload: AnyCodable? = nil, vector: VectorScoredPointVector? = nil) {
        self.id = id
        self.version = version
        self.score = score
        self.payload = payload
        self.vector = vector
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case version
        case score
        case payload
        case vector
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(score, forKey: .score)
        try container.encodeIfPresent(payload, forKey: .payload)
        try container.encodeIfPresent(vector, forKey: .vector)
    }
}

