//
// VectorSearchParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VectorSearchParams: Codable, JSONEncodable, Hashable {

    public var hnswEf: Int?
    public var exact: Bool? = false
    public var quantization: VectorSearchParamsQuantization?

    public init(hnswEf: Int? = nil, exact: Bool? = false, quantization: VectorSearchParamsQuantization? = nil) {
        self.hnswEf = hnswEf
        self.exact = exact
        self.quantization = quantization
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hnswEf = "hnsw_ef"
        case exact
        case quantization
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hnswEf, forKey: .hnswEf)
        try container.encodeIfPresent(exact, forKey: .exact)
        try container.encodeIfPresent(quantization, forKey: .quantization)
    }
}

