//
// VisorListGPUs200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VisorListGPUs200Response: Codable, JSONEncodable, Hashable {

    public var gpus: [VisorGpuView]?

    public init(gpus: [VisorGpuView]? = nil) {
        self.gpus = gpus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gpus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gpus, forKey: .gpus)
    }
}

